"""
Ellenőrzi melyik ZENE_SONGS-ban lévő dalnak van Spotify preview_url-je.
Futtatás: python3 check_spotify_previews.py <CLIENT_ID> <CLIENT_SECRET>
"""
import sys, requests, json, time

CLIENT_ID     = sys.argv[1] if len(sys.argv) > 1 else input("Client ID: ").strip()
CLIENT_SECRET = sys.argv[2] if len(sys.argv) > 2 else input("Client Secret: ").strip()

# --- Token lekérés (Client Credentials flow) ---
resp = requests.post(
    "https://accounts.spotify.com/api/token",
    data={"grant_type": "client_credentials"},
    auth=(CLIENT_ID, CLIENT_SECRET),
)
resp.raise_for_status()
token = resp.json()["access_token"]
headers = {"Authorization": f"Bearer {token}"}

# --- Track ID-k kinyerése a ZENE_SONGS listából ---
SONG_IDS = [
    ("Queen","Bohemian Rhapsody","2zImmNYRMK61rOsLyqtihJ",49),
    ("Michael Jackson","Thriller","4hqdY15wwLs9MEjROHDBkX",95),
    ("Ed Sheeran","Shape of You","7qiZfU4dY1lWllzX7mPBI3",15),
    ("The Weeknd","Blinding Lights","0VjIjW4GlUZAMYd2vXMi3b",20),
    ("Bruno Mars","Uptown Funk","32OlwWuMpZ6b0aN2RZOeMS",22),
    ("Adele","Rolling in the Deep","1c8gk2PeTE04A1pIDH9YMk",15),
    ("Tones and I","Dance Monkey","02R5Ks5qZc44ZHnOHNV27i",16),
    ("Luis Fonsi","Despacito","6habFhsOp2NvshLv26DqMb",15),
    ("Adele","Someone Like You","1zwMYTA5nlNjZxYrvBB2pV",53),
    ("Billie Eilish","Bad Guy","2Fxmhks0bxGSBdJ92vM42m",10),
    ("Camila Cabello","Havana","4OigJoW7KVYAjBj2Azc6tw",17),
    ("Justin Timberlake","Can't Stop the Feeling","75ImJaMYx2HgVNolZtGMs2",24),
    ("Dua Lipa","Levitating","39LLxExYz6ewLAcYrzQQyP",45),
    ("ABBA","Dancing Queen","7efXqi3qE5CPlx0N41o1Vm",28),
    ("Eminem","Lose Yourself","5Z01UMMf7V1o0MzF86s6WJ",20),
    ("Coldplay","Yellow","4lIYjf9rjhRYduh8BKGWyZ",45),
    ("Arctic Monkeys","Do I Wanna Know?","5FVd6KXrgO9B3JPmC8OPst",10),
    ("Imagine Dragons","Believer","0pqnGHJpmpxLKifKRmU6WP",10),
    ("The Beatles","Let It Be","5V1AHQugSTASVez5ffJtFo",62),
    ("Sam Smith","Stay With Me","5Nm9ERjJZ5oyfXZTECKmRt",30),
    ("Pharrell Williams","Happy","60nZcImufyMA1MKQY3dcCH",16),
    ("Dua Lipa","Don't Start Now","3PfIrDoz19wz7qK7tYeu62",20),
    ("Lady Gaga","Bad Romance","2gHExpSSt1BTOHI7QoIJeL",20),
    ("Lady Gaga","Poker Face","2FRnf9qhLbvw8fu4IBXx78",32),
    ("Katy Perry","Roar","3A374B5cdMNccW0irQcn7E",42),
    ("Katy Perry","Firework","3jjujdWJ20bPsWAHxBUYgV",45),
    ("Katy Perry","Teenage Dream","1yvr6BkfZHexJO6M43jzNZ",30),
    ("Rihanna","Umbrella","0k6dYiIFZWwrVSLaohOSEN",45),
    ("Rihanna","Diamonds","1C2QJNTmsTxCDBuIgai8QV",18),
    ("Calvin Harris","We Found Love","4O7QzMK0sMoQOliKFcXe4O",12),
    ("Justin Bieber","Sorry","09CtPGIpYB4BrO8qb1RGsF",17),
    ("Justin Bieber","Love Yourself","3UmaczJpikHgJFyBTAJVoz",45),
    ("Ariana Grande","Thank U, Next","3e9HZxeyfWwjeyPAMmWSSQ",30),
    ("Ariana Grande","7 Rings","6ocbgoVGwYJhOv1GgI9NsF",15),
    ("Post Malone","Circles","21jGcNKet2qwijlDFuPiPb",20),
    ("Post Malone","Sunflower","3KkXRkHbMCARz0aVfEt68P",55),
    ("Drake","God's Plan","6DCZcSspjsKoFjzjrWoCdn",10),
    ("Taylor Swift","Shake It Off","0cqRj7pUJDkTCEsJkx8snD",38),
    ("Taylor Swift","Blank Space","1CS7Sd1u5tWkstBhpssyjP",25),
    ("Taylor Swift","Anti-Hero","0V3wPSX9ztLhV0P4doZtzh",10),
    ("Coldplay","Viva la Vida","1mea3bSkSGXuIRvnydlB5b",30),
    ("Coldplay","Fix You","7LVHVU3tWfcxj5aiPFEW4Q",70),
    ("Coldplay","The Scientist","75JFxkI2RXiU7L9VXzMkle",12),
    ("Maroon 5","Animals","4KyR7fZkEkw6pAXYuFiJp6",18),
    ("Maroon 5","Moves Like Jagger","5yG3ZAhTHXT6WViPRrCFsC",35),
    ("Maroon 5","Girls Like You","3e9S5bnMKX5kQMhBVt2Mif",15),
    ("Maroon 5","Sugar","4JehYebiI9242HG1szlAhX",34),
    ("The Chainsmokers","Closer","7BKLCZ1jbUBVqRi2FVlTdp",30),
    ("Imagine Dragons","Radioactive","69yfbpvmkQ9Lpe3X2UMcnu",45),
    ("Imagine Dragons","Thunder","1zB4vmk8tFRmM9UULNzbLB",15),
    ("Imagine Dragons","Enemy","5QO79kh1waicV47BqGRL3g",10),
    ("OneRepublic","Counting Stars","2tznHmp70mOZEFe1tkFMm3",42),
    ("OneRepublic","Apologize","4K4iP54RIUaFb1xKiUvEI9",10),
    ("Ed Sheeran","Perfect","0tgVpDi06FyKpA1z0VMD4v",14),
    ("Ed Sheeran","Thinking Out Loud","34gCuhDGsG4bRPIf9bb02f",60),
    ("Ed Sheeran","Bad Habits","6PQ88X9ohnZsIVDNHiHdCp",18),
    ("Shawn Mendes","Stitches","1R0a2iXumgCiFb7geUgIsX",8),
    ("Shawn Mendes","Treat You Better","3SWqUBFjJBqOIVlQCxJeUS",12),
    ("Charlie Puth","See You Again","2QbMejIfABdjmm7NHfMrPx",30),
    ("Charlie Puth","Attention","3AJwUDP919kvQ9QcozQPxg",20),
    ("Marshmello","Happier","4PUImXFwNYpMIliKGUuOYH",20),
    ("Kygo","Firestone","7n2Ycct7Beij7Dj7meI4X0",25),
    ("Clean Bandit","Rather Be","6IZpRPKBMFRIyUbGJAhSEm",25),
    ("Clean Bandit","Rockabye","5kqIPrATaCc2RqpSMxJEGQ",32),
    ("Avicii","Wake Me Up","6YQmqP7VRNPK8jIFNhsVKi",38),
    ("Avicii","Levels","4ioGNJEOdGBqHwmDiEfEeJ",25),
    ("Avicii","The Nights","0ct6r3EGTcMLPtrXHDvVjc",18),
    ("David Guetta","Titanium","0TeZFqSMfSFBc4UXZmVSEM",55),
    ("David Guetta","Without You","39QRChYEuG9kWYfLjrJFqO",48),
    ("Martin Garrix","Animals","5J0F3bRLU5EqvEuiDDoEVi",35),
    ("Alan Walker","Faded","7lPN2DXiMsVn7XUKtOW1CS",14),
    ("Alan Walker","Alone","3qUAMkTVTLHPOPfUXANVXE",20),
    ("Sia","Chandelier","4PEHM4bWNxsCHJrpQ9QgLz",40),
    ("Sia","Cheap Thrills","19Sg3GelBhAnH14tAVODGX",18),
    ("Sia","Elastic Heart","5IqU3iHDW7oDQB0iEPBrBm",15),
    ("Billie Eilish","Ocean Eyes","6S9a80fsm1jJqzJOfG4Mfy",10),
    ("Billie Eilish","Happier Than Ever","2BHjBHPbXJx2VSwBqUTvVR",50),
    ("Harry Styles","Watermelon Sugar","6UelLqGlWMcVH1E5c4H7lY",20),
    ("Harry Styles","As It Was","4Dvkj6JhhA12EX05fT7y2e",22),
    ("Olivia Rodrigo","drivers license","6Sp17ZnQRVInd2gDSt9Wem",55),
    ("Olivia Rodrigo","good 4 u","6PERH6vv58sNeFill3zlQn",10),
    ("The Kid LAROI","Stay","5HCyWlXZPP0y6Eo96Q2NGB",12),
    ("Glass Animals","Heat Waves","02MWAaffLxlfxAUY7c5dvx",40),
    ("Doja Cat","Say So","5b88tNINg4Q4nrRR2riqnG",22),
    ("Doja Cat","Kiss Me More","748mdHapucKQyPQFowb6eQ",15),
    ("Lil Nas X","Old Town Road","2YpeDb67231RjR0MgVLzsG",8),
    ("Lil Nas X","MONTERO","2RoX9JLQW3aOolKYJBGTZk",12),
    ("BTS","Dynamite","5QDLhrAOJJdNAmCTJ8xMyW",14),
    ("BTS","Butter","11dFghVXANMlKmJXsNCbNl",8),
    ("Queen","Don't Stop Me Now","5T8EDUDqKcs6OSOwEsfqG7",18),
    ("Queen","We Will Rock You","54flyrjcdnQdco7300NbMZ",5),
    ("Queen","We Are the Champions","7AAveEx8yOhWMrHAEOHYyP",30),
    ("Michael Jackson","Billie Jean","5ChkMS8OtdzJeqyybCc9R5",28),
    ("Michael Jackson","Beat It","6x1BHx7UYIMJ6BTcXrNtao",18),
    ("Michael Jackson","Black or White","4iZ4pt7kvcaH6Yo8UoZ4s2",55),
    ("AC/DC","Highway to Hell","2zYzyRzz6pRmhPzyfh38I3",18),
    ("AC/DC","Back in Black","08mG3Y1vljYA6bvDt4Wqkj",10),
    ("Guns N Roses","Sweet Child O' Mine","7o2CTH4ctstm8TNelqjb51",14),
    ("Guns N Roses","Welcome to the Jungle","0eFQAGOqgIEszEwGKZqjb3",5),
    ("Nirvana","Smells Like Teen Spirit","5ghIJDpPoe3CfHMGu71E6T",5),
    ("Nirvana","Come as You Are","0M7XxkfNfC3qhKlBfm6s6F",10),
    ("Red Hot Chili Peppers","Under the Bridge","3d9DCcoMkHkSn3SAhLAHMf",55),
    ("Red Hot Chili Peppers","Californication","0NxNNXnRDQBX3rQN06M0gB",60),
    ("Linkin Park","In the End","60a0Rd6pjrkxjPbaKzXjfq",12),
    ("Linkin Park","Numb","1nJvji2KIlWSseXRSlNYsC",18),
    ("Metallica","Enter Sandman","3KfrPCXNVbPOUcCAP9TDQS",20),
    ("U2","With or Without You","1xVCDpxFGtCH0ExTnvFs3A",60),
    ("The Police","Every Breath You Take","6OmhkSOpvYBokMKQxpIGx2",5),
    ("Bon Jovi","Livin' on a Prayer","37gAZndmPqDmTsWBSGSMvN",60),
    ("Bon Jovi","It's My Life","6nnQFenT3DjcwJp1RQM4V4",20),
    ("Journey","Don't Stop Believin'","4bHsxqR3GMrXTxEPLuK5ue",45),
    ("Europe","The Final Countdown","3QHZ5SYGAQG9CvMWrGBnVl",8),
    ("Toto","Africa","2374M0fQpWi3dLnB54qaLX",38),
    ("Roxette","The Look","2XSa5IzRMBQf7TbJmHGJAr",12),
    ("Roxette","It Must Have Been Love","2H7PHVdQ3mXqEHXcvclTB0",10),
    ("ABBA","Mamma Mia","3DLFxrxBvnhqFoTpT1DFRq",14),
    ("ABBA","Waterloo","2uQbj2rMRVGBJZpFCQFRVo",8),
    ("Michael Bublé","Haven't Met You Yet","4kflIgIlbSTaQNiSXuqOhM",42),
    ("Bruno Mars","Just the Way You Are","1WkMMavIMc4JZ8cfMmxHkI",20),
    ("Bruno Mars","Grenade","4kSGbjWGxLwowRPP6dn8vN",15),
    ("Bruno Mars","Treasure","55h7vJchibLdUkxdlX3fK7",20),
    ("Bruno Mars","Locked Out of Heaven","1t0ObfJMZIGnrY1F69EiNe",10),
    ("P!nk","Just Give Me a Reason","3pLdWdkj83EYfDN6H2N8MR",48),
    ("P!nk","Raise Your Glass","7JhWJBkckMWS5sL6h6bODT",12),
    ("Alicia Keys","Empire State of Mind","41ro5cHJ1QdU1K8gfEEP4n",12),
    ("Alicia Keys","Girl on Fire","4JehYebiI9242HG1szlAhY",30),
    ("Nicki Minaj","Super Bass","4cFyZq5cApFmC0CfSFfGjl",38),
    ("Cardi B","Bodak Yellow","5jZ2pBbwxmV3nuX3UFUMsA",12),
    ("Lizzo","Truth Hurts","6KgBpzTuTRPebChN0VTyzV",12),
    ("Lizzo","Good as Hell","6KgBpzTuTRPebChN0VTyzX",28),
    ("Halsey","Without Me","3qYZleGnePpPBrqJPnEXEw",12),
    ("Billie Eilish","Therefore I Am","5GbEFKXRHo6WvVQDZUoY1v",12),
    ("Dua Lipa","New Rules","2ekn2ttSfGqwhhate0LSR0",45),
    ("Dua Lipa","Physical","4OddF6MQpzm6Km2kFxBJLd",20),
    ("The Weeknd","Starboy","7MXVkk9YMctZqd1Srtv4MB",12),
    ("The Weeknd","Save Your Tears","6lanRgr6wXibZr8KgzXxBl",10),
    ("The Weeknd","Earned It","34gCuhDGsG4bRPIf9bb02a",28),
    ("Post Malone","Rockstar","5UqCQaDshKOIoHFoQKoXPo",20),
    ("Post Malone","Better Now","3CBDaO8KWxHjJwQM0DoeOM",18),
    ("Drake","Hotline Bling","0kwjjS0cMSFgp72GeqJU5q",25),
    ("Drake","One Dance","1xznGGDl6giTHxMF7Jus56",12),
    ("Kendrick Lamar","HUMBLE.","7KXjTSCq5nL1LoYtL7XAwS",12),
    ("Kanye West","Stronger","6oIrCHCgf8FnIbzekTDnpR",5),
    ("Jay-Z","Empire State of Mind","41ro5cHJ1QdU1K8gfEEP4n",12),
    ("Eminem","Without Me","7lQ8MOhq6IN2w8EYcFNSUk",10),
    ("Eminem","Slim Shady","5ORnKhLahU5NnMGgn7DTRE",14),
    ("50 Cent","In da Club","2HhVRCCcCjRJQ5dBMWGmAZ",10),
    ("Outkast","Hey Ya!","4bt3s7GGFmQKSShLFYWNRp",15),
    ("The Black Eyed Peas","I Gotta Feeling","5qqabIl2vWzo9ApSC317sa",10),
    ("The Black Eyed Peas","Where Is the Love?","2PdDSO8D7EPe6kFuVEZNqP",55),
    ("Pitbull","Give Me Everything","6BI7UfFKXb2eKSO6BbFNqx",20),
    ("LMFAO","Party Rock Anthem","6Ij4JMFD5YEKN2ZiEMd4A6",35),
    ("Psy","Gangnam Style","03UrZgTINDqvnUMbbIMhql",20),
    ("Gotye","Somebody That I Used to Know","1dnSgWPYWPMqIABMVDlCYz",55),
    ("Foster the People","Pumped Up Kicks","7w87IxuO7BDcJ3YUqCyMTT",22),
    ("Fun.","We Are Young","3QGsuHI8jO1Rx4JWLUh9jd",38),
    ("Passenger","Let Her Go","3aaS4oCiSEFlcJQDFDlnzL",55),
    ("James Arthur","Say You Won't Let Go","5JCoSi02qi3jJeHXBsxeAV",35),
    ("Lewis Capaldi","Someone You Loved","7BjP2fMEBhbGM6y3Ug3qQv",42),
    ("Lewis Capaldi","Before You Go","1Cv1YLb4q0RzL6pybtaMLo",45),
    ("Ruth B.","Lost Boy","2SBuMxFVeQBgwqnzr8J9PI",5),
    ("John Legend","All of Me","3U4isOIWM3VvDubwSI3y7a",45),
    ("Bruno Mars","When I Was Your Man","0nJW01T7XtvILxQgC5J7Wh",50),
    ("Ed Sheeran","The A Team","2TbSYJBTHNBHSHNMvDjTmj",20),
    ("Sam Smith","Writing's on the Wall","0bRLhHdFj3HLdAHx5Dl7KD",50),
    ("Adele","Hello","4sPmO7WMQUAf45kwMOtONw",20),
    ("Adele","Skyfall","2EcDLxnxrwHRGijHUCZPnC",45),
    ("Adele","Easy On Me","6oKy7mhSZnvHSmHFP9BjVj",12),
    ("Amy Winehouse","Rehab","4GFXZ1ZDNXpV06MlFNEqxQ",5),
    ("Amy Winehouse","Back to Black","6uelj0w3EO8KhMOHXKtWKO",20),
    ("Norah Jones","Come Away with Me","0sRDpBBFY0o3sK7pJBETRn",25),
    ("Alicia Keys","If I Ain't Got You","3ifSZzZPV6CdAGW0IbFyL6",45),
    ("John Mayer","Your Body Is a Wonderland","1yjreFenolkBFrR1VMHMv4",50),
    ("Jack Johnson","Better Together","0qhFHPkiRCqrNuHnpWCkDX",5),
    ("Jason Mraz","I'm Yours","1EzrEOXmMH3G43AXT1y7pA",20),
    ("Train","Hey, Soul Sister","3AWxHCYwmFODHMeGHrALep",10),
    ("Hozier","Take Me to Church","1CS7Sd1u5tWkstBhpss0xk",50),
    ("Vance Joy","Riptide","6uelj0w3EO8KhMOHXKtWKP",8),
    ("Kodaline","All I Want","7KXjTSCq5nL1LoYtL7XAwa",55),
    ("Bastille","Pompeii","1YBDW8WKUMhGGMCC4gXSzc",25),
    ("Bastille","Good Grief","3CXCjHkFcN5OuBL8lrBBzd",35),
    ("Years & Years","King","3VDNKL9HQxWVHqxwHzXSqO",22),
    ("Troye Sivan","Youth","1PekFPvCvjHlqMJ5LcmqxS",25),
    ("Zara Larsson","Lush Life","3Zy1CVhBenIMBLZNDJlUpO",18),
    ("Zara Larsson","Never Forget You","5oNHMbBDRPWNhUaKUGDa39",32),
    ("Selena Gomez","Come & Get It","3wjzPHl3vMpA0lEEHVsU4y",45),
    ("Selena Gomez","Good for You","2Bk2DuRkHQ3U5SY7rcwnE8",28),
    ("Selena Gomez","Lose You to Love Me","2v3x8ViCLSQXuVHClmFJmf",12),
    ("Miley Cyrus","Wrecking Ball","6Qyc6fS4DsZjB2mRW9DsQs",50),
    ("Miley Cyrus","Flowers","4Dvkj6JhhA12EX05fT7y3e",15),
    ("Lizzo","Juice","6KgBpzTuTRPebChN0VTyzY",10),
    ("Cardi B","WAP","6pN0OhqFPFZbzZTEsDGF5D",15),
    ("Nicki Minaj","Starships","0HYHTQPE9Bxbzow9X8SaFz",30),
    ("Beyoncé","Halo","0FDzzruyVECATHjKnHczu0",55),
    ("Beyoncé","Crazy in Love","7BymdCBrSlZ17lRhEYJfxg",18),
    ("Beyoncé","Single Ladies","7BzSqd3PTbSdjtiqo6KAyh",8),
    ("Destiny's Child","Say My Name","5gtM2E8H6D52CqcDqTzDjD",12),
    ("TLC","No Scrubs","5S1sAmFCOaCKnRWvXpFpYH",12),
    ("Spice Girls","Wannabe","1Je1IMUlBXfWoHnkPqF1bU",5),
    ("Backstreet Boys","I Want It That Way","1BkPDiLE9kNQmSVyMtBpIP",5),
    ("Backstreet Boys","Everybody","3cEqMXe2K8MbH0xSyWoBmP",38),
    ("*NSYNC","Bye Bye Bye","3B4gXCxGPHCbfFDrI0MlP8",5),
    ("Britney Spears","Baby One More Time","3MjUtNVVq3C8Fn0MP3zhXa",8),
    ("Britney Spears","Toxic","6I9VnuOl0nhCJQH5KBZL4K",12),
    ("Christina Aguilera","Beautiful","7oSL0VFBdq3xBN4PdEQOUV",12),
    ("Jennifer Lopez","Jenny from the Block","2r5OyiEHfJCTcBFMUMmIUz",12),
    ("Shakira","Hips Don't Lie","0GmSmocmP9XBHBCBV0IpD8",42),
    ("Enrique Iglesias","Hero","5s2J3gEYRiQBOLrqX5mSXX",38),
    ("Enrique Iglesias","Bailamos","5s2J3gEYRiQBOLrqX5mSXY",20),
    ("Ricky Martin","Livin' la Vida Loca","3fbRB7UkxBN3DLHXMmZR3X",8),
    ("Carlos Santana","Smooth","7BkoHpNaFkIqaAdEIpEIRG",28),
    ("Nelly","Hot in Herre","2VBpiDLzNI42aS9O2Xt0hy",18),
    ("Usher","Yeah!","2PpruBYCo4H7WOBJ7Q2EwM",10),
    ("Usher","Burn","5XcrNXYJHydmGPlOEDoiuX",42),
    ("Mariah Carey","All I Want for Christmas","0bAsR2unSRefkMoMqiTX8S",18),
    ("Wham!","Last Christmas","2FRnf9qhLbvw8fu4IBXx78b",5),
    ("Michael Bublé","It's Beginning to Look a Lot Like Christmas","70LcF31zb1H0PyJoS1Sx1r",8),
    ("George Michael","Careless Whisper","2LD2gT7gwAurzdQDwtxZoT",8),
    ("Elton John","Crocodile Rock","7GhIk7El126fd3jCZEBIOJ",8),
    ("Elton John","Tiny Dancer","2TVmEYKzStfEXaK9V0OJKV",60),
    ("David Bowie","Heroes","7Jh1bpe76CNTCgdgAdBw4Z",45),
    ("David Bowie","Space Oddity","72Z17vmmeQKAg8bptWvpVG",35),
    ("Fleetwood Mac","Dreams","0ofHAoxe9vBkTCp2UQIavz",38),
    ("Eagles","Hotel California","40riOy7x9W7GXjyGp4pjAv",60),
    ("Pink Floyd","Another Brick in the Wall","0WneGInT1h7tz9ZNTlNzgO",5),
    ("Led Zeppelin","Stairway to Heaven","5CQ30WqJwcep0pYcV4AMNc",120),
    ("The Rolling Stones","Paint It Black","77LbSyNujHy5SvEpfgBKKa",8),
    ("The Rolling Stones","Satisfaction","3Y4GHgQflDOhfVnHMRDXvr",8),
    ("The Doors","Riders on the Storm","1VrMk9OcXelRq5DI0RizLP",10),
    ("Aerosmith","Dream On","3IkHSXSHOPMT6JJXZRIYTN",100),
    ("Aerosmith","I Don't Want to Miss a Thing","4wfFmMjYbz9UBnBxRMvmxj",50),
    ("The Killers","Mr. Brightside","7d3a2aFRFRPOCENRjJzZMf",5),
    ("The Killers","Human","4uGNDXIOIF4oP3yJCMOkKr",45),
    ("Muse","Uprising","4VqPOruhp5EdPBeR92t6lQ",20),
    ("Muse","Madness","5SJatTL59FQcSVPINTKlPo",50),
    ("Radiohead","Creep","70LcF31zb1H0PyJoS1Sx1o",20),
    ("Oasis","Wonderwall","2s2LS2IFcV5vOmW5rDyHMN",55),
    ("Snow Patrol","Chasing Cars","4TnjEaWOeW0eKTKIEvJyCa",8),
    ("Keane","Somewhere Only We Know","1MQTmpYWZ5N4cMOkM7kMOE",18),
    ("James Blunt","You're Beautiful","4BKfNLJaIqHp6zW9FyGcUd",10),
    ("Robbie Williams","Angels","73CMnFHXCG3BwPrSFLaIg5",42),
    ("Take That","Back for Good","6MvRKBiuXWGHqUvB0w7qHm",12),
    ("Alanis Morissette","Ironic","61mWefnWQOLe90wb05fy7x",18),
    ("No Doubt","Don't Speak","1YMdGGBdxC5m8KKDU1Amsp",18),
    ("Green Day","Basket Case","13FEzaFCa61VE0CHR8dSXr",5),
    ("Green Day","Boulevard of Broken Dreams","1DkR8NOmBDmhZ7kFNMOYwR",5),
    ("Blink-182","All the Small Things","6K4t31amsSzgjBCUOa1dUU",5),
    ("Sum 41","In Too Deep","6RHXJnQpMGJHzBaB5p9cqj",25),
    ("Paramore","Misery Business","0YFxBPjS2FM9J8aAzGRx3K",12),
    ("Evanescence","Bring Me to Life","2nkto6YNI4rUYTLqEwWJ3o",35),
    ("Three Days Grace","I Hate Everything About You","3KAeqBr1mkElB2fFMuHDXM",35),
    ("Nickelback","How You Remind Me","6Ow8aHJJHBT3lTpxaH6Gdi",12),
    ("Creed","With Arms Wide Open","5PbmSnQUbIqeEXDCFVVWMb",35),
    ("Smash Mouth","All Star","3cfOd4CMv2snFaKAnMdnvK",8),
    ("Outkast","Ms. Jackson","3bm7yGlj5tRHQqSUMFNX4g",15),
    ("Kelis","Milkshake","3VC8QqOhSvHBRYOiB8SXQX",8),
    ("Wheatus","Teenage Dirtbag","2KHRENHSgbRMmSm5MVEYZF",40),
    ("The Offspring","Pretty Fly","6e0rJHhJPMFO8pNw4X3mj9",15),
    ("Limp Bizkit","Nookie","6wjZBGKcBUxhm7kh0n8VoK",15),
    ("Gorillaz","Feel Good Inc.","0d28khcov6AiegSCpG5TuT",22),
    ("Gorillaz","DARE","3X8skX0pHXwMYJd9cVlf3e",12),
    ("White Stripes","Seven Nation Army","7oK9tBG5sKDblbczRhg7B9",5),
    ("Franz Ferdinand","Take Me Out","0IzHIGxDfPJVrdNoWW4CPo",55),
    ("Interpol","Slow Hands","5DJqVkW2NWMhGHKaP4BpPH",30),
    ("Kaiser Chiefs","Ruby","24UWPxgY8X7bNkVmMdxP64",10),
    ("Amy Winehouse","Valerie","7x4HBQvfTDpCcFVeHxaMHi",38),
    ("Duffy","Mercy","3Hs3wvIFGjp4l8DfxiJOjd",12),
    ("Ellie Goulding","Lights","3JUNajJe8KWXL0eHB4IShF",20),
    ("Ellie Goulding","Love Me Like You Do","77pWCp1SqSqmHzSnmBNFYg",12),
    ("Lorde","Royals","4pklpe2NYqIRqk5gCZ0hpt",10),
    ("Lorde","Tennis Court","6C5iXTQPnOqnHzDnBFENzD",25),
    ("Lana Del Rey","Summertime Sadness","0F4rlqkfqMhvqyFCEG2HMH",50),
    ("Lana Del Rey","Video Games","6pEQY3a7OVP8QpEpSEjcKE",35),
    ("Florence + Machine","Dog Days Are Over","6UGJBwd0oFKRwj3FCUQ4bL",45),
    ("MGMT","Kids","7JIuqL4ZqkpfGKQhYlrirs",30),
    ("Vampire Weekend","A-Punk","3kwZUWLWF8JfIHiJALqOPn",5),
    ("Tame Impala","The Less I Know the Better","6K4t31amsSzgjBCUOa1dUY",30),
    ("Tame Impala","Let It Happen","6TZ6bRSNbpRV2qOJirPkFT",5),
    ("Childish Gambino","Redbone","4LpSFGGjGsMBZqeEWz0M7Y",55),
    ("Frank Ocean","Thinking Bout You","0kGKfkzJa16NdRMWGXJjTz",35),
    ("SZA","Good Days","4CT3rN63xMRBpT83AXTFDH",25),
    ("H.E.R.","Hard Place","7FsVQQlEEJaYwPSwrKZBIW",45),
    ("Silk Sonic","Leave the Door Open","7AzlLxHn24DxjgQX73F9fU",18),
    ("Doja Cat","Need to Know","6Hv2KCxJkB2tB0nGt2ORSJ",12),
    ("Giveon","Heartbreak Anniversary","52x1oCBHSCRfbqIOfOlbsC",25),
    ("Daniel Caesar","Best Part","5snHnFenCZyLXFKD7EqDIG",30),
    ("Coldplay","A Sky Full of Stars","2dpaYNEQHiRxtZbfNsse99",35),
    ("Imagine Dragons","Natural","7GKJeABn3YP5BXJZL6dCnD",12),
    ("Twenty One Pilots","Stressed Out","3CRDbSIZ4r5MsZ0YwxzbA7",10),
    ("Twenty One Pilots","Heathens","6i0V12jOa3mr6uu4WBOAdA",35),
    ("Fall Out Boy","Sugar We're Goin Down","0kLOqkO9OHDVefM3xAMifK",18),
    ("My Chemical Romance","Welcome to the Black Parade","7D3QD4873o5mSBfVPpVJqC",40),
    ("Panic! at the Disco","I Write Sins Not Tragedies","6QgjcU0zLnzq5OrUoSZ3OK",30),
    ("Walk the Moon","Shut Up and Dance","4kbj5MwxO1bq9wjT5g9HaA",40),
    ("OneRepublic","I Lived","5l8oJWKYAz5KxIWIkmRGUq",30),
    ("X Ambassadors","Renegades","0YFxBPjS2FM9J8aAzGRx3L",12),
    ("Macklemore & Ryan Lewis","Thrift Shop","0UBVuALHG6SROQ7bWrF9Gz",35),
    ("Macklemore & Ryan Lewis","Can't Hold Us","3bidbhpOYeVtu9oise3nAG",30),
    ("Robin Thicke","Blurred Lines","6mBYXepGPDGiX2ngNK1X5G",10),
    ("Iggy Azalea","Fancy","2OuooBVHVKSSSfbElNTKu3",10),
    ("Meghan Trainor","All About That Bass","0mNaHoEBLgPhlCfO53lBE1",15),
    ("Mark Ronson","Uptown Funk","32OlwWuMpZ6b0aN2RZOeMS",22),
    ("Flo Rida","Good Feeling","5V4EIeNUivBGQSr4GYjUbF",15),
    ("Ne-Yo","So Sick","2vNbmFqCXxfOCrpnHY6I3B",10),
    ("Timbaland","The Way I Are","3Y4GHgQflDOhfVnHMRDXvs",22),
    ("T-Pain","Buy U a Drank","7Jh1bpe76CNTCgdgAdBw4A",18),
    ("Akon","Beautiful","7oSL0VFBdq3xBN4PdEQOUW",15),
    ("Akon","Lonely","3YcVfDKNVaqwYMZzNdqsFr",12),
    ("Sean Paul","Temperature","5qTBrDXx11x9EBvQbJBKON",10),
    ("Jason Derulo","Talk Dirty","3AJwUDP919kvQ9QcozQPxb",20),
    ("Jason Derulo","Wiggle","3AJwUDP919kvQ9QcozQPxc",15),
    ("Major Lazer","Lean On","6E6R0tJMw3pnlcMmqmhFwc",30),
    ("OMI","Cheerleader","17KKWSW1rDhEJxPJBczd2a",18),
    ("Stromae","Alors On Danse","3SWqUBFjJBqOIVlQCxJeUa",15),
    ("Stromae","Papaoutai","2Fxmhks0bxGSBdJ92vM42n",30),
    ("Sia","Titanium","0TeZFqSMfSFBc4UXZmVSEa",55),
    ("Zedd","The Middle","5TXOAXX18ySA06Mv4hMXi7",35),
    ("Zedd","Beautiful Now","1eHWnDLSmH0bKj9BAPB9em",40),
    ("Disclosure","Latch","2Lq2qT3sTGE3fCxOT5xpWK",40),
    ("Sam Smith","Lay Me Down","0bRLhHdFj3HLdAHx5Dl7Ka",35),
    ("Sam Smith","Too Good at Goodbyes","5DqSPEbIkPWDcHUqfbHUL4",15),
    ("George Ezra","Budapest","0DqFiMEzqWkmQ3GI0dVjk1",8),
    ("George Ezra","Shotgun","7FVYkOYX5UHkBt1T1J0d3K",20),
    ("Ben Howard","Keep Your Head Up","2HhVRCCcCjRJQ5dBMWGmAa",5),
    ("Mumford & Sons","I Will Wait","74sClFKLh8RYS0RZMJYZ7X",50),
    ("Mumford & Sons","The Cave","6VQ9pYkFkgFJbLvjnWcMNd",38),
    ("Of Monsters and Men","Little Talks","1YBDW8WKUMhGGMCC4gXSzd",45),
    ("Birdy","Skinny Love","7BKLCZ1jbUBVqRi2FVlTda",20),
    ("Kodaline","The One","7KXjTSCq5nL1LoYtL7XAwb",50),
    ("Gabrielle Aplin","The Power of Love","7ZGbTLwp4M0Dp6Uld4qRvP",40),
    ("Paloma Faith","Only Love Can Hurt Like This","1BkPDiLE9kNQmSVyMtBpIa",38),
    ("Jessie J","Price Tag","1JhYjVoXMtHnI13URZGJ2v",30),
    ("Jessie J","Domino","0eFQAGOqgIEszEwGKZqjba",30),
    ("Olly Murs","Troublemaker","3AxRoD7M3yOvWBXBgAtfS0",25),
    ("Gotye","Eyes Wide Open","1dnSgWPYWPMqIABMVDlCYa",30),
    ("Ben Howard","Only Love","2HhVRCCcCjRJQ5dBMWGmAb",12),
    ("Kodaline","High Hopes","7KXjTSCq5nL1LoYtL7XAwc",55),
    ("Hozier","From Eden","1CS7Sd1u5tWkstBhpss0xl",30),
    ("Bon Iver","Skinny Love","1UGD3lW3tDmgZfAVDh6w7r",8),
    ("The Lumineers","Ho Hey","1BkPDiLE9kNQmSVyMtBpIb",5),
]

# Deduplicate by spotifyId
seen = {}
for s in SONG_IDS:
    seen[s[2]] = s

unique_songs = list(seen.values())

print(f"\nÖsszes dal: {len(unique_songs)}")
print("Spotify API ellenőrzés...\n")

has_preview = []
no_preview  = []
not_found   = []

# Batch 50-esével
ids = [s[2] for s in unique_songs]
for i in range(0, len(ids), 50):
    batch = ids[i:i+50]
    r = requests.get(
        "https://api.spotify.com/v1/tracks",
        headers=headers,
        params={"ids": ",".join(batch), "market": "HU"}
    )
    if r.status_code == 429:
        wait = int(r.headers.get("Retry-After", 5))
        print(f"Rate limit, várakozás {wait}s...")
        time.sleep(wait)
        r = requests.get("https://api.spotify.com/v1/tracks", headers=headers, params={"ids": ",".join(batch), "market": "HU"})
    r.raise_for_status()
    tracks = r.json().get("tracks", [])
    for track, sid in zip(tracks, batch):
        song = seen[sid]
        label = f"{song[0]} — {song[1]}"
        if track is None:
            not_found.append((label, sid))
        elif track.get("preview_url"):
            has_preview.append((label, sid, track["preview_url"], song[3]))
        else:
            no_preview.append((label, sid))
    time.sleep(0.1)

print(f"✅ Van preview ({len(has_preview)} db):")
for label, sid, url, start in has_preview:
    print(f"  {label}  [{sid}]")

print(f"\n❌ Nincs preview ({len(no_preview)} db):")
for label, sid in no_preview:
    print(f"  {label}  [{sid}]")

if not_found:
    print(f"\n⚠️  Nem található ({len(not_found)} db):")
    for label, sid in not_found:
        print(f"  {label}  [{sid}]")

print(f"\nÖsszegzés: {len(has_preview)}/{len(unique_songs)} dalnak van preview ({100*len(has_preview)//len(unique_songs)}%)")

# JSON kimenet a szűrt listához
with open("songs_with_preview.json", "w") as f:
    json.dump([{"artist": seen[sid][0], "title": seen[sid][1], "spotifyId": sid, "start": seen[sid][3], "previewUrl": url}
               for label, sid, url, start in has_preview], f, ensure_ascii=False, indent=2)
print("\n→ songs_with_preview.json elmentve (az index.html-hez használható szűrt lista)")
