import re

NEW_IGAZ_HAMIS = '''const IGAZ_HAMIS = [
  { text:'Az ember szíve percenként átlagosan 60–100-szor ver.', igaz:true, cat:'🫀 Emberi test', exp:'Normál nyugalmi pulzus 60-100/perc között van.' },
  { text:'Magyarország fővárosa Debrecen.', igaz:false, cat:'🌍 Földrajz', exp:'Magyarország fővárosa Budapest.' },
  { text:'A gyémánt a legeményebb természetes anyag a Földön.', igaz:true, cat:'🔬 Tudomány', exp:'A gyémánt a Mohs-skálán 10-es, ez a maximum.' },
  { text:'A cápa emlős állat.', igaz:false, cat:'🐾 Állatok', exp:'A cápa hal, nem emlős.' },
  { text:'A Nílus a világ leghosszabb folyója.', igaz:true, cat:'🌍 Földrajz', exp:'A Nílus kb. 6650 km hosszú.' },
  { text:'A kávé Kínából ered.', igaz:false, cat:'🍔 Étel & Ital', exp:'A kávé Etiópiából ered.' },
  { text:'Az alkohol valójában melegít a hidegtől.', igaz:false, cat:'💡 Érdekesség', exp:'Az alkohol tágítja az ereket, így hőveszteséget okoz.' },
  { text:'A csimpánz az ember legközelebbi élő rokona.', igaz:true, cat:'🐾 Állatok', exp:'A csimpánz DNS-e ~98.7%-ban megegyezik az emberével.' },
  { text:'A Hold saját fényt bocsát ki.', igaz:false, cat:'🔬 Tudomány', exp:'A Hold a Nap fényét veri vissza.' },
  { text:'Az oktopusznak három szíve van.', igaz:true, cat:'🐾 Állatok', exp:'Két kopoltyúszív és egy rendszerszív.' },
  { text:'A denevér teljesen vak állat.', igaz:false, cat:'🐾 Állatok', exp:'A denevérnek van látása, de echolokációt is használ.' },
  { text:'A víz pontosan 0°C-on fagy meg normál légnyomáson.', igaz:true, cat:'🔬 Tudomány', exp:'0°C = 273.15 K a víz fagyáspontja 1 atm nyomáson.' },
  { text:'Mozart 35 éves korában halt meg.', igaz:true, cat:'📜 Történelem', exp:'Mozart 1756-ban született és 1791-ben halt meg.' },
  { text:'A Titanic 1912-ben süllyedt el.', igaz:true, cat:'📜 Történelem', exp:'1912. április 15-én süllyedt el az Atlanti-óceánban.' },
  { text:'Az emberi testnek 206 csontja van felnőttkorban.', igaz:true, cat:'🫀 Emberi test', exp:'Csecsemőknek ~270 csontjuk van, ezek összenőnek.' },
  { text:'Európa a világ legkisebb kontinense.', igaz:false, cat:'🌍 Földrajz', exp:'Ausztrália a legkisebb kontinens.' },
  { text:'A fény sebessége kb. 300 000 km/s.', igaz:true, cat:'🔬 Tudomány', exp:'Pontosan 299 792 458 m/s vákuumban.' },
  { text:'A struccok homokba dugják a fejüket, ha megijednek.', igaz:false, cat:'🐾 Állatok', exp:'Ez egy mítosz — a struccok nem csinálnak ilyet.' },
  { text:'A méhek elpusztulnak, miután egyszer megcsíptek valakit.', igaz:true, cat:'🐾 Állatok', exp:'A fullánk kiszakad a bőrből, és a méh meghal.' },
  { text:'Az arany nem oldódik sósavban.', igaz:true, cat:'🔬 Tudomány', exp:'Az arany csak királyvízben oldódik (HCl+HNO3 keverék).' },
  { text:'Az emberi agy kb. 86 milliárd neuronból áll.', igaz:true, cat:'🫀 Emberi test', exp:'Modern becslések szerint kb. 86 milliárd neuron van.' },
  { text:'Az ember bőre a test legsúlyosabb szerve.', igaz:true, cat:'🫀 Emberi test', exp:'A bőr átlagosan 4-5 kg-ot nyom és 1.5-2 m² területű.' },
  { text:'A fogak csontból állnak.', igaz:false, cat:'🫀 Emberi test', exp:'A fogak zománcból, dentinből és pulpából állnak, nem csontból.' },
  { text:'Az emberi szem kb. 10 millió színt tud megkülönböztetni.', igaz:true, cat:'🫀 Emberi test', exp:'Az emberi szem valóban képes ~10 millió színárnyalat elkülönítésére.' },
  { text:'A máj a test legnagyobb belső szerve.', igaz:true, cat:'🫀 Emberi test', exp:'A máj átlagosan 1.5 kg, ez a legnagyobb belső szerv.' },
  { text:'Az ember egyetlen sejtje tartalmazza a teljes DNS-t.', igaz:true, cat:'🫀 Emberi test', exp:'Majdnem minden sejtben ott van a teljes ~3 milliárd bázispár.' },
  { text:'A vér 90%-a vízből áll.', igaz:false, cat:'🫀 Emberi test', exp:'A vérplazma ~90% víz, de a teljes vér ~80% víztartalmú.' },
  { text:'Az embernek 32 foga van teljesen kifejlődve.', igaz:true, cat:'🫀 Emberi test', exp:'32 fog a bölcsességfogakkal együtt.' },
  { text:'A köldök utáni élet első lélegzete tüdőgyulladást okoz.', igaz:false, cat:'🫀 Emberi test', exp:'Az első lélegzet normális és szükséges, nem okoz betegséget.' },
  { text:'Az emberi gyomorsav felolvasztja a pengét.', igaz:false, cat:'🫀 Emberi test', exp:'A gyomorsav (pH 1.5-3.5) nem oldja fel a fémeket ilyen gyorsan.' },
  { text:'Az emberi test kb. 60%-a vízből áll.', igaz:true, cat:'🫀 Emberi test', exp:'Felnőtteknél az arány 55-65% között van.' },
  { text:'A vörös vérsejtek sejtmagot tartalmaznak.', igaz:false, cat:'🫀 Emberi test', exp:'Az érett vörösvérsejtek elveszítik sejtmagjukat fejlődés során.' },
  { text:'Az ujjlenyomat élethosszig változatlan marad.', igaz:true, cat:'🫀 Emberi test', exp:'Az ujjlenyomat mintázata genetikailag meghatározott és állandó.' },
  { text:'Az ember egyetlen szempillája átlagosan 5 évig nő.', igaz:false, cat:'🫀 Emberi test', exp:'A szempilla kb. 3-5 hónapig nő, nem évig.' },
  { text:'A bal agy irányítja a test jobb oldalát.', igaz:true, cat:'🫀 Emberi test', exp:'Az agyféltekék keresztbe irányítják a test ellentétes oldalát.' },
  { text:'Az emberi test összes erezete kb. 100 000 km hosszú.', igaz:true, cat:'🫀 Emberi test', exp:'Az erek összesített hossza eléri a ~100 000 km-t.' },
  { text:'A gyomor nem termel savat éhgyomorra.', igaz:false, cat:'🫀 Emberi test', exp:'A gyomor folyamatosan termel savat, ételtől függetlenül.' },
  { text:'Az ember körme átlagosan havonta 3 mm-t nő.', igaz:true, cat:'🫀 Emberi test', exp:'A köröm kb. 3-4 mm-t nő havonta, a hajnál lassabban.' },
  { text:'A szív bal kamrája nagyobb, mint a jobb.', igaz:false, cat:'🫀 Emberi test', exp:'A bal és jobb kamra hasonló méretű, de a bal falazata vastagabb.' },
  { text:'Az ember naponta átlagosan 23 000-szer lélegzik.', igaz:true, cat:'🫀 Emberi test', exp:'Percenként ~16 légvétel × 1440 perc ≈ 23 000 légvétel naponta.' },
  { text:'A Föld bolygó tömegének nagy részét a kéreg teszi ki.', igaz:false, cat:'🌍 Földrajz', exp:'A kéreg a Föld tömegének csak ~1%-a, a köpeny és mag adja a többit.' },
  { text:'Az Amazonas a világ leghosszabb folyója.', igaz:false, cat:'🌍 Földrajz', exp:'A Nílus a leghosszabb (~6650 km), az Amazonas a legnagyobb vízhozamú.' },
  { text:'Japán több mint 6000 szigetből áll.', igaz:true, cat:'🌍 Földrajz', exp:'Japánnak kb. 6852 szigete van.' },
  { text:'Az Északi-sark egy jégtömb, ami szárazföldön van.', igaz:false, cat:'🌍 Földrajz', exp:'Az Északi-sark tengeri jég, nem szárazföld. A Déli-sark van szárazföldön.' },
  { text:'A Szahara a világ legnagyobb sivataga.', igaz:false, cat:'🌍 Földrajz', exp:'Az Antarktika a legnagyobb sivatag (~14 millió km²), a Szahara második.' },
  { text:'Magyarország területe kb. 93 000 km².', igaz:true, cat:'🌍 Földrajz', exp:'Magyarország területe pontosan 93 028 km².' },
  { text:'A Duna Magyarország leghosszabb folyója.', igaz:false, cat:'🌍 Földrajz', exp:'A Tisza a leghosszabb Magyarországon belüli folyó (~597 km).' },
  { text:'Ausztrália egyszerre ország és kontinens.', igaz:true, cat:'🌍 Földrajz', exp:'Ausztrália az egyetlen ország, ami egész kontinenst foglal el.' },
  { text:'A Himalája a világ leghosszabb hegylánca.', igaz:false, cat:'🌍 Földrajz', exp:'Az Andok a leghosszabb hegylánc (~7000 km).' },
  { text:'Az Egyenlítő Afrika déli részén halad át.', igaz:false, cat:'🌍 Földrajz', exp:'Az Egyenlítő Afrika közepén, Kenyán, Kongón stb. halad át.' },
  { text:'Az Atlanti-óceán nagyobb a Csendes-óceánnál.', igaz:false, cat:'🌍 Földrajz', exp:'A Csendes-óceán a legnagyobb, kb. kétszer akkora mint az Atlanti.' },
  { text:'Kanada a világ második legnagyobb országa területileg.', igaz:true, cat:'🌍 Földrajz', exp:'Kanada 9.98 millió km², Oroszország után a második.' },
  { text:'A Balaton Közép-Európa legnagyobb tava.', igaz:true, cat:'🌍 Földrajz', exp:'A Balaton 593 km², Közép-Európa legnagyobb sekély tava.' },
  { text:'Brazília az egyetlen portugál nyelvű ország Dél-Amerikában.', igaz:true, cat:'🌍 Földrajz', exp:'A többi dél-amerikai ország spanyol vagy más nyelvű.' },
  { text:'A Velencei-tó Magyarország második legnagyobb tava.', igaz:true, cat:'🌍 Földrajz', exp:'A Velencei-tó ~26 km², a Balaton után a második legnagyobb.' },
  { text:'Az Északi-tenger az Atlanti-óceán része.', igaz:true, cat:'🌍 Földrajz', exp:'Az Északi-tenger egy peremtenger, az Atlanti-óceánhoz tartozik.' },
  { text:'Görögország több mint 2000 szigettel rendelkezik.', igaz:true, cat:'🌍 Földrajz', exp:'Görögországnak kb. 2000 szigete és szigetecskéje van.' },
  { text:'A Duna Bécsből ered.', igaz:false, cat:'🌍 Földrajz', exp:'A Duna a Fekete-erdőből ered Németországban.' },
  { text:'Afrikában van a legtöbb ország a világon.', igaz:true, cat:'🌍 Földrajz', exp:'Afrikában 54 ország van, ez a legtöbb bármely kontinensen.' },
  { text:'Az Egyenlítőtől távolabb erősebb a gravitáció.', igaz:true, cat:'🌍 Földrajz', exp:'A Földnél a sarkok közelebb vannak a Föld középpontjához.' },
  { text:'A víz forráspontja mindig 100°C.', igaz:false, cat:'🔬 Tudomány', exp:'A forráspont függ a légnyomástól — pl. hegyen alacsonyabb.' },
  { text:'Az atomok belseje szinte teljesen üres.', igaz:true, cat:'🔬 Tudomány', exp:'Az atom tömegének 99.9%-a a parányi atommagban összpontosul.' },
  { text:'A hang gyorsabban terjed a levegőben, mint a vízben.', igaz:false, cat:'🔬 Tudomány', exp:'A hang vízben ~1480 m/s, levegőben csak ~343 m/s sebességű.' },
  { text:'Az elektromosság sebessége azonos a fény sebességével.', igaz:false, cat:'🔬 Tudomány', exp:'Az elektromos jel kb. a fénysebesség 60-90%-án halad.' },
  { text:'A Naprendszer egyetlen csillaga a Nap.', igaz:true, cat:'🔬 Tudomány', exp:'A Naprendszernek csak egy csillaga van, a Nap.' },
  { text:'A Mars légköre szén-dioxidból áll főként.', igaz:true, cat:'🔬 Tudomány', exp:'A Mars légköre ~95% szén-dioxid.' },
  { text:'A radioaktív bomlás megállítható hűtéssel.', igaz:false, cat:'🔬 Tudomány', exp:'A radioaktív bomlás fizikai és kémiai körülményektől független.' },
  { text:'Az elektron negatív töltésű részecske.', igaz:true, cat:'🔬 Tudomány', exp:'Az elektron -1 töltéssel rendelkezik.' },
  { text:'A fekete lyukakból semmi sem tud kiszabadulni.', igaz:false, cat:'🔬 Tudomány', exp:'Hawking-sugárzás formájában energia kiszivároghat belőlük.' },
  { text:'A szén-dioxid nem éghető gáz.', igaz:true, cat:'🔬 Tudomány', exp:'A CO2 nem éghető, sőt tűzoltásra is használják.' },
  { text:'A Naprendszer bolygói közül a Szaturnusz a legnagyobb.', igaz:false, cat:'🔬 Tudomány', exp:'A Jupiter a legnagyobb bolygó a Naprendszerben.' },
  { text:'A DNS kettős hélix szerkezetét Watson és Crick írta le.', igaz:true, cat:'🔬 Tudomány', exp:'Watson és Crick 1953-ban publikálták a DNS szerkezetét.' },
  { text:'A Hold kb. 384 000 km-re van a Földtől.', igaz:true, cat:'🔬 Tudomány', exp:'Az átlagos távolság kb. 384 400 km.' },
  { text:'A hélium éghető gáz.', igaz:false, cat:'🔬 Tudomány', exp:'A hélium nemesgáz, nem éghető. A hidrogén az éghető.' },
  { text:'A Naprendszer 8 bolygóból áll.', igaz:true, cat:'🔬 Tudomány', exp:'2006 óta 8 bolygó van — a Plutót törpebolygóvá minősítették.' },
  { text:'A Vénusz a Naprendszer legforróbb bolygója.', igaz:true, cat:'🔬 Tudomány', exp:'A Vénusz felszíni hőmérséklete ~465°C, a Merkúrnál is forróbb.' },
  { text:'A gravitáció gyorsítja az időt.', igaz:false, cat:'🔬 Tudomány', exp:'Az erős gravitáció lassítja az időt (általános relativitás).' },
  { text:'A klorofill adja a növények zöld színét.', igaz:true, cat:'🔬 Tudomány', exp:'A klorofill a fotoszintézis kulcsmolekulája, és zöld színű.' },
  { text:'Az emberi DNS kb. 50%-ban azonos a banánéval.', igaz:true, cat:'🔬 Tudomány', exp:'Meglepő, de kb. 50-60% az egyezés az alapvető génekben.' },
  { text:'A fehér fény egyetlen tiszta színből áll.', igaz:false, cat:'🔬 Tudomány', exp:'A fehér fény az összes látható szín keveréke.' },
  { text:'A Holdon nincs légkör.', igaz:true, cat:'🔬 Tudomány', exp:'A Holdnak rendkívül ritka exoszférája van, de valódi légköre nincs.' },
  { text:'Az oroszlán az összes nagy macska közül a legerősebb harapással bír.', igaz:false, cat:'🐾 Állatok', exp:'A jaguárnak van a legerősebb harapása a nagy macskák között.' },
  { text:'A delfinek valójában halak.', igaz:false, cat:'🐾 Állatok', exp:'A delfin emlős, tüdővel lélegzik, és szoptatja kölykét.' },
  { text:'A zsiráf a világ legmagasabb szárazföldi állata.', igaz:true, cat:'🐾 Állatok', exp:'A zsiráf akár 5-6 méteres magasságot is elérhet.' },
  { text:'A pingvinek kizárólag a Déli-sarkon élnek.', igaz:false, cat:'🐾 Állatok', exp:'Pingvinek élnek Dél-Amerikában, Afrikában és Ausztráliában is.' },
  { text:'A krokodilok legközelebbi rokonai a gyíkok.', igaz:false, cat:'🐾 Állatok', exp:'A krokodilok legközelebbi rokonai a madarak és a tuatarák.' },
  { text:'A méhek ötoldalú sejteket (pentagont) építenek.', igaz:false, cat:'🐾 Állatok', exp:'A méhek hatszögű (hexagon) sejteket építenek.' },
  { text:'A koala medve nem valódi medve.', igaz:true, cat:'🐾 Állatok', exp:'A koala erszényes állat, nem igazi medve.' },
  { text:'A kenguru első lábait nem tudja egyszerre mozgatni.', igaz:true, cat:'🐾 Állatok', exp:'A kenguru első lábait csak egymástól függetlenül tudja mozgatni.' },
  { text:'A pillangó lábaival ízleli az ételét.', igaz:true, cat:'🐾 Állatok', exp:'A pillangó ízérzékelői a lábain találhatók.' },
  { text:'A tintahal vért használ légzésre, nem oxigént.', igaz:false, cat:'🐾 Állatok', exp:'A tintahal is oxigént lélegez, de kék vére (hemocianin) van.' },
  { text:'A kacsa hangja nem visszhanggal.', igaz:false, cat:'🐾 Állatok', exp:'Ez egy mítosz — a kacsa hangja természetesen visszaverődik.' },
  { text:'A lajhár hetente egyszer megy le a fáról.', igaz:true, cat:'🐾 Állatok', exp:'A lajhár kb. heti egyszer ereszkedik le végzükre.' },
  { text:'Az elefánt az egyetlen állat, amelyik nem tud ugrani.', igaz:true, cat:'🐾 Állatok', exp:'Az elefánt fizikailag képtelen mind a négy lábát egyszerre a levegőbe emelni.' },
  { text:'A teknős él a legtovább az állatok közül.', igaz:false, cat:'🐾 Állatok', exp:'Egyes halfajok (pl. Grönlandi cápa) tovább élhetnek 400+ évet.' },
  { text:'A ló egyujjú állat.', igaz:true, cat:'🐾 Állatok', exp:'A ló csülke egyetlen ujj evolúciós maradványa.' },
  { text:'A flamingó természetesen rózsaszín.', igaz:false, cat:'🐾 Állatok', exp:'A flamingó fiókája fehér — a rákfélék fogyasztásától lesz rózsaszín.' },
  { text:'A gorillának emberhez hasonló vércsoport-rendszere van.', igaz:true, cat:'🐾 Állatok', exp:'A főemlősöknek ABO vércsoportrendszerük van, hasonlóan az emberhez.' },
  { text:'A hólepke lárvaként él a legtovább.', igaz:false, cat:'🐾 Állatok', exp:'Egyes bogarak (pl. tücsök) töltik évekig lárvastádiumban.' },
  { text:'Az arktikus sarki róka a leghidegebb éghajlaton él.', igaz:true, cat:'🐾 Állatok', exp:'A sarki róka -70°C-on is életben marad.' },
  { text:'A kígyók nem hallatnak hangot.', igaz:false, cat:'🐾 Állatok', exp:'Egyes kígyók, pl. a csörgőkígyó hangot hallat csörgőjével.' },
  { text:'A csillaghal képes regenerálni elveszett karjait.', igaz:true, cat:'🐾 Állatok', exp:'A tengericsillag elveszett karját teljesen újra tudja növeszteni.' },
  { text:'A kínai Nagy Fal az űrből is látható szabad szemmel.', igaz:false, cat:'💡 Érdekesség', exp:'Az űrből szabad szemmel nem látható — ez egy elterjedt tévhit.' },
  { text:'Az emberi ujjlenyomatok egyediek, még az ikrekéi is.', igaz:true, cat:'💡 Érdekesség', exp:'Az azonos ikrek DNS-e megegyezhet, de ujjlenyomatuk különböző.' },
  { text:'A banán bogyótermés.', igaz:true, cat:'💡 Érdekesség', exp:'Botanikailag a banán bogyó, az eper viszont nem.' },
  { text:'A paradicsomot zöldségnek tekinti a tudomány.', igaz:false, cat:'💡 Érdekesség', exp:'Botanikailag a paradicsom gyümölcs (bogyó), bár konyhailag zöldség.' },
  { text:'Az ejtőernyő feltalálója maga is kipróbálta azt.', igaz:true, cat:'💡 Érdekesség', exp:'Louis-Sébastien Lenormand 1783-ban ugrott le egy toronyról.' },
  { text:'A Rubik-kocka egy magyar találmány.', igaz:true, cat:'💡 Érdekesség', exp:'Rubik Ernő 1974-ben találta fel Budapesten.' },
  { text:'A villám soha nem csap kétszer ugyanoda.', igaz:false, cat:'💡 Érdekesség', exp:'A villám rendszeresen csap ugyanoda — pl. tornyokra, fákra.' },
  { text:'Az emberi köldök egy hegforradás.', igaz:true, cat:'💡 Érdekesség', exp:'A köldök a köldökzsinór elvágásának helye, hegesedve marad.' },
  { text:'A számítógépes egér neve az alakjából ered.', igaz:true, cat:'💡 Érdekesség', exp:'Az egér neve a kábele miatti egerszerű kinézetből ered.' },
  { text:'A Coca-Cola eredeti receptje tartalmazott kokalevelet.', igaz:true, cat:'💡 Érdekesség', exp:'Az eredeti recept valóban tartalmazott kokalevél-kivonatot.' },
  { text:'Az összes bolygó neve mitológiai istenség után kapta nevét.', igaz:false, cat:'💡 Érdekesség', exp:'A Föld neve nem mitológiai istenségről ered.' },
  { text:'A legtöbb ember jobban emlékszik rossz eseményekre, mint jókra.', igaz:true, cat:'💡 Érdekesség', exp:'Ez a negativitási torzítás — az agy erősebben kódolja a negatív emlékeket.' },
  { text:'A méz soha nem romlik el.', igaz:true, cat:'💡 Érdekesség', exp:'Az egyiptomi sírokban talált méz évezredek után is ehető volt.' },
  { text:'A karatéban a fekete öv a legmagasabb fokozat.', igaz:false, cat:'💡 Érdekesség', exp:'A fekete öv felett is léteznek magasabb danok (piros, fehér-piros szalag stb.).' },
  { text:'Az ókori Olimpián a sportolók meztelenül versenyeztek.', igaz:true, cat:'💡 Érdekesség', exp:'Az ókori görög olimpiai versenyzők valóban ruhátlanul versenyeztek.' },
  { text:'A kólában nincs koffein.', igaz:false, cat:'💡 Érdekesség', exp:'A kóla tartalmaz koffeint, kb. 30-40 mg/330 ml.' },
  { text:'A vászonba csomagolt múmia magasabb hőmérsékleten bomlik.', igaz:false, cat:'💡 Érdekesség', exp:'A vászon szigeteli a múmiát, lassítva a bomlást.' },
  { text:'A jégkrém Kínában jelent meg először.', igaz:true, cat:'💡 Érdekesség', exp:'A kínaiak hóból és gyümölcsléből készítettek fagyasztott desszertet kb. 200 BC körül.' },
  { text:'Az első számítógépes program szerzője egy nő volt.', igaz:true, cat:'💡 Érdekesség', exp:'Ada Lovelace írta az első algoritmust Babbage analitikus gépéhez (1843).' },
  { text:'Az első autó lóereje valóban kevesebb volt egy ló erejénél.', igaz:true, cat:'💡 Érdekesség', exp:'Az első Benz Patent-Motorwagen csak 0.75 lóerős volt (1885).' },
  { text:'A Holdra való utazás rövidebb ideig tartott, mint Magyarországról Ausztráliába repülni.', igaz:false, cat:'💡 Érdekesség', exp:'Az Apollo-11 útja 3 nap 3 óra volt — a Sydney-i repülés kb. 22 óra.' },
  { text:'Az ókori Rómában deodoranst használtak.', igaz:true, cat:'💡 Érdekesség', exp:'A rómaiak gyantából és timsóból készített kenőcsöket használtak.' },
  { text:'Az első mobiltelefon 1973-ban készült el.', igaz:true, cat:'💡 Érdekesség', exp:'Martin Cooper mutatta be az első mobilt 1973. április 3-án.' },
  { text:'A Római Birodalom 476-ban omlott össze.', igaz:true, cat:'📜 Történelem', exp:'476-ban esett el Nyugat-Róma. Kelet-Róma (Bizánc) 1453-ig állt fenn.' },
  { text:'Kleopátra egyiptomi volt.', igaz:false, cat:'📜 Történelem', exp:'Kleopátra görög (makedón) származású volt, a Ptolemaida dinasztiából.' },
  { text:'A második világháború 1939-ben kezdődött.', igaz:true, cat:'📜 Történelem', exp:'Németország 1939. szeptember 1-jén támadta meg Lengyelországot.' },
  { text:'Nagy Sándor soha nem veszített csatát.', igaz:true, cat:'📜 Történelem', exp:'Nagy Sándor hadjárataiban egyetlen csatát sem veszített el.' },
  { text:'A Hold első embere Neil Armstrong volt.', igaz:true, cat:'📜 Történelem', exp:'Neil Armstrong 1969. július 21-én lépett először a Holdra.' },
  { text:'A berlini fal 1989-ben dőlt le.', igaz:true, cat:'📜 Történelem', exp:'1989. november 9-én nyitották meg a falat.' },
  { text:'Az első atombombát Japánra dobták.', igaz:true, cat:'📜 Történelem', exp:'1945. augusztus 6-án Hirosimára, 9-én Nagaszakira dobták.' },
  { text:'Napóleon alacsony termetű volt.', igaz:false, cat:'📜 Történelem', exp:'Napóleon 1.69 m magas volt, ez a kor átlagos férfi magassága.' },
  { text:'Columbus Kristóf 1492-ben érte el Amerikát.', igaz:true, cat:'📜 Történelem', exp:'1492. október 12-én kötött ki a Bahama-szigeteken.' },
  { text:'Az első olimpia az újkorban 1896-ban volt Athénban.', igaz:true, cat:'📜 Történelem', exp:'Az első modern olimpiát 1896-ban rendezték Athénban.' },
  { text:'Lenin 1924-ben halt meg.', igaz:true, cat:'📜 Történelem', exp:'Lenin 1924. január 21-én halt meg agyvérzésben.' },
  { text:'Az első ember az űrben amerikai volt.', igaz:false, cat:'📜 Történelem', exp:'Jurij Gagarin szovjet űrhajós volt az első ember az űrben (1961).' },
  { text:'A Magna Carta 1215-ben íródott.', igaz:true, cat:'📜 Történelem', exp:'A Magna Cartát 1215-ben írta alá II. János angol király.' },
  { text:'Az ókori egyiptomiak nem tudtak írni.', igaz:false, cat:'📜 Történelem', exp:'Az egyiptomiak fejlett hieroglif írásrendszert használtak.' },
  { text:'A hidegháborúban soha nem volt fegyveres összecsapás.', igaz:false, cat:'📜 Történelem', exp:'Korea, Vietnam és más háborúkban lőttek egymásra a felek.' },
  { text:'Mátyás király reneszánsz udvarát tartotta fenn.', igaz:true, cat:'📜 Történelem', exp:'Mátyás egyik legjelentősebb reneszánsz udvart vezette Európában.' },
  { text:'Az ókori görögök demokráciát találtak fel.', igaz:true, cat:'📜 Történelem', exp:'Athénban alakult ki az első demokratikus rendszer ~500 BC körül.' },
  { text:'A francia forradalom 1789-ben kezdődött.', igaz:true, cat:'📜 Történelem', exp:'A Bastille ostroma 1789. július 14-én volt.' },
  { text:'A Trianoni békét 1920-ban írták alá.', igaz:true, cat:'📜 Történelem', exp:'1920. június 4-én írták alá a Versailles melletti Nagy-Trianon kastélyban.' },
  { text:'Az első világháborút az Osztrák-Magyar Monarchia nyerte.', igaz:false, cat:'📜 Történelem', exp:'Az első világháborúban az Osztrák-Magyar Monarchia veszített.' },
  { text:'A Star Wars első epizódja 1977-ben jelent meg.', igaz:true, cat:'🎬 Film & Zene', exp:'Az első Star Wars film (Epizód IV) 1977. május 25-én mutatták be.' },
  { text:'A Titanic film 1997-ben James Cameron rendezte.', igaz:true, cat:'🎬 Film & Zene', exp:'A Titanic 1997-es film James Cameron rendezésében készült.' },
  { text:'Michael Jackson az "1999" dalt énekelte.', igaz:false, cat:'🎬 Film & Zene', exp:'Az "1999" Prince dala, nem Michael Jacksoné.' },
  { text:'A Beatles négy tagból állt.', igaz:true, cat:'🎬 Film & Zene', exp:'John, Paul, George és Ringo alkotta a Beatlest.' },
  { text:'Az Oroszlánkirály eredeti zenéjét Elton John szerezte.', igaz:false, cat:'🎬 Film & Zene', exp:'Hans Zimmer szerezte a zenét, Elton John dalokat írt a filmhez.' },
  { text:'A Schindler listája fekete-fehér film.', igaz:true, cat:'🎬 Film & Zene', exp:'Spielberg szándékosan fekete-fehérben forgatta a filmet.' },
  { text:'A Metallica 1981-ben alakult.', igaz:true, cat:'🎬 Film & Zene', exp:'A Metallicát 1981-ben alapították Los Angelesben.' },
  { text:'Az Avatar (2009) a legtöbb bevételt hozó film valaha.', igaz:true, cat:'🎬 Film & Zene', exp:'Az Avatar 2022-es újra-bemutatóval együtt a legtöbb bevételű film.' },
  { text:'Freddie Mercury brit állampolgár volt.', igaz:false, cat:'🎬 Film & Zene', exp:'Freddie Mercury Zanzibáron (ma Tanzánia) született, zanzibar-iráni származású.' },
  { text:'A Mozart nevű filmben Tom Hanks játszott.', igaz:false, cat:'🎬 Film & Zene', exp:'Az Amadeus (1984) főszereplője F. Murray Abraham és Tom Hulce volt.' },
  { text:'A Pulp Fiction Quentin Tarantino rendezése.', igaz:true, cat:'🎬 Film & Zene', exp:'A Pulp Fictiont Tarantino rendezte 1994-ben.' },
  { text:'Az ABBA svéd együttes.', igaz:true, cat:'🎬 Film & Zene', exp:'Az ABBA tagjai: Agnetha, Björn, Benny és Anni-Frid — mind svédek.' },
  { text:'A Gyűrűk Ura trilógiát Új-Zélandon forgatták.', igaz:true, cat:'🎬 Film & Zene', exp:'Peter Jackson a saját hazájában, Új-Zélandon forgatta a filmeket.' },
  { text:'Elvis Presley és Johnny Cash egy időben éltek.', igaz:true, cat:'🎬 Film & Zene', exp:'Mindketten az 1950-es években lettek híresek, Elvis 1977-ben, Cash 2003-ban halt meg.' },
  { text:'A Nirvana frontembere Kurt Cobain volt.', igaz:true, cat:'🎬 Film & Zene', exp:'Kurt Cobain volt a Nirvana énekese és gitárosa.' },
  { text:'A James Bond-filmsorozat regények alapján készült.', igaz:true, cat:'🎬 Film & Zene', exp:'Ian Fleming regényei alapján készültek az eredeti filmek.' },
  { text:'A Rolling Stones 1962-ben alakult.', igaz:true, cat:'🎬 Film & Zene', exp:'A Rolling Stonest 1962-ben alapította Mick Jagger és Keith Richards.' },
  { text:'A Mozart 41 szimfóniát komponált.', igaz:true, cat:'🎬 Film & Zene', exp:'Mozartnak 41 szimfóniája ismert, bár egyes kutatók más számot is mondanak.' },
  { text:'A Harry Potter könyvsorozatot J.K. Rowling írta.', igaz:true, cat:'🎬 Film & Zene', exp:'Joanne K. Rowling 1997-ben adta ki az első Harry Potter kötetet.' },
  { text:'Beethoven az ötödik szimfóniáját teljesen süketen írta.', igaz:false, cat:'🎬 Film & Zene', exp:'Az ötödik szimfónia (1808) idején Beethoven még hallott részben.' },
  { text:'A FIFA labdarúgó-világbajnokságot négyévente rendezik.', igaz:true, cat:'⚽ Sport', exp:'A vb 1930 óta (néhány kivételtől eltekintve) négyévente zajlik.' },
  { text:'Magyarország valaha nyert olimpiai aranyat labdarúgásban.', igaz:true, cat:'⚽ Sport', exp:'Magyarország 1952-ben és 1964-ben is olimpiai bajnok lett labdarúgásban.' },
  { text:'A teniszben a "love" nullát jelent.', igaz:true, cat:'⚽ Sport', exp:'A teniszben a love = 0, a 15, 30, 40 a pontszámok.' },
  { text:'A kosárlabdát James Naismith találta fel.', igaz:true, cat:'⚽ Sport', exp:'James Naismith 1891-ben találta fel a kosárlabdát Kanadában.' },
  { text:'A maratoni futás pontosan 42 km.', igaz:false, cat:'⚽ Sport', exp:'A maraton pontos távolsága 42.195 km.' },
  { text:'Roger Federer svájci teniszező.', igaz:true, cat:'⚽ Sport', exp:'Roger Federer Basel-ben született, svájci állampolgár.' },
  { text:'A Tour de France minden évben júliusban ér véget Párizsban.', igaz:true, cat:'⚽ Sport', exp:'A Tour hagyományosan júliusban zajlik és a Champs-Élysées-n fejeződik be.' },
  { text:'A judo japán harcművészet.', igaz:true, cat:'⚽ Sport', exp:'A judót Jigoro Kano alapította 1882-ben Japánban.' },
  { text:'A sumo birkózásban a kisebb versenyző soha nem győzhet.', igaz:false, cat:'⚽ Sport', exp:'Technikával kisebb versenyző is megverheti a nagyobbet.' },
  { text:'Az első modern olimpián nők is versenyeztek.', igaz:false, cat:'⚽ Sport', exp:'Az 1896-os athéni olimpián csak férfiak vehettek részt.' },
  { text:'A Formula–1 autók nem tudnak fejjel lefelé hajtani.', igaz:false, cat:'⚽ Sport', exp:'Az F1 autók nagy sebességnél elegendő leszorítóerőt termelnek ehhez.' },
  { text:'A sakk Indiából ered.', igaz:true, cat:'⚽ Sport', exp:'A sakkot kb. az 5. századi Indiában találták fel (chaturanga).' },
  { text:'Puskás Ferenc 84 válogatott gólt szerzett.', igaz:true, cat:'⚽ Sport', exp:'Puskás Ferenc 84 gólt szerzett a magyar válogatottban.' },
  { text:'A rögbi és az amerikaifoci azonos sport.', igaz:false, cat:'⚽ Sport', exp:'Hasonló eredetük van, de eltérő szabályokkal különálló sportok.' },
  { text:'A boksz olimpiai sport.', igaz:true, cat:'⚽ Sport', exp:'A boksz 1904 óta (kisebb megszakításokkal) olimpiai sportág.' },
  { text:'A vízilabdát Magyarországon találták fel.', igaz:false, cat:'⚽ Sport', exp:'A vízilabdát Skóciában és Angliában fejlesztették ki a 19. században.' },
  { text:'Usain Bolt jamaicai sprinter.', igaz:true, cat:'⚽ Sport', exp:'Usain Bolt Jamaicában született, a 100 m és 200 m világrekordere.' },
  { text:'A szumó Japán nemzeti sportja.', igaz:true, cat:'⚽ Sport', exp:'A szumó birkózást Japán nemzeti sportjának tekintik.' },
  { text:'A kávé fogyasztása csökkenti az álmosságot.', igaz:true, cat:'🍔 Étel & Ital', exp:'A koffein blokkolja az adenozin receptorokat, csökkentve az álmosságot.' },
  { text:'A sör eredetileg nem tartalmazott komlót.', igaz:true, cat:'🍔 Étel & Ital', exp:'Az ókori sörök gabonából és fűszerekből készültek, komló nélkül.' },
  { text:'A csokoládé mérgező a kutyák számára.', igaz:true, cat:'🍔 Étel & Ital', exp:'A csokoládé teobromin-tartalma mérgező a kutyáknak.' },
  { text:'A vörös és fehér bor ugyanabból a szőlőből készülhet.', igaz:true, cat:'🍔 Étel & Ital', exp:'Egyes vörös szőlőfajták fehér borhoz is feldolgozhatók, és fordítva.' },
  { text:'A tokaji aszú hungarikum.', igaz:true, cat:'🍔 Étel & Ital', exp:'A tokaji aszút UNESCO-védett hungarikumként tartják számon.' },
  { text:'A görög joghurt Görögországból ered.', igaz:false, cat:'🍔 Étel & Ital', exp:'A sűrített joghurt az egész Közel-Keleten és a Balkánon hagyományos, nem kizárólag görög.' },
  { text:'A pizza Olaszországból ered.', igaz:true, cat:'🍔 Étel & Ital', exp:'A modern pizza Nápolyban alakult ki a 18-19. században.' },
  { text:'A pezsgő Angliában jött létre.', igaz:false, cat:'🍔 Étel & Ital', exp:'A pezsgő a champagne-i régióból (Franciaország) ered.' },
  { text:'A zöld tea és a fekete tea ugyanabból a növényből készül.', igaz:true, cat:'🍔 Étel & Ital', exp:'Mindkettő a Camellia sinensis növény leveléből készül, a feldolgozás különbözik.' },
  { text:'A whisky Írországból és Skóciából is ered.', igaz:true, cat:'🍔 Étel & Ital', exp:'Mindkét országnak saját whisk(e)y hagyománya van.' },
  { text:'A csípős paprika csípősségét a kapszaicin okozza.', igaz:true, cat:'🍔 Étel & Ital', exp:'A kapszaicin a paprika csípős vegyülete, mértéke a Scoville-skálán mérhető.' },
  { text:'A sushi nyersen fogyasztott halból áll mindig.', igaz:false, cat:'🍔 Étel & Ital', exp:'A sushi fő összetevője a fűszerezett rizs — feltétje lehet nyers hal, de nem kötelező.' },
  { text:'A gulyás egy magyar étel.', igaz:true, cat:'🍔 Étel & Ital', exp:'A gulyás (gulyásleves) Magyarország egyik leghíresebb nemzeti étele.' },
  { text:'A narancslé sok C-vitamint tartalmaz.', igaz:true, cat:'🍔 Étel & Ital', exp:'100 ml narancslé kb. 40-50 mg C-vitamint tartalmaz.' },
  { text:'A víz kalóriamentes.', igaz:true, cat:'🍔 Étel & Ital', exp:'A tiszta víznek nincs kalóriatartalma.' },
  { text:'A champagne-i régión kívül készült pezsgőt is lehet champagne-nak nevezni.', igaz:false, cat:'🍔 Étel & Ital', exp:'Az EU-ban csak a champagne-i régióból származó pezsgő viselheti ezt a nevet.' },
  { text:'A mozzarella eredetileg bivalytejből készül.', igaz:true, cat:'🍔 Étel & Ital', exp:'Az eredeti mozzarella di bufala valóban bivalytejből készül Dél-Olaszországban.' },
  { text:'A kovász nélküli kenyér nem kel meg sütéskor.', igaz:true, cat:'🍔 Étel & Ital', exp:'Kovász (vagy élesztő) nélkül a kenyér lapos marad, nem kel.' },
  { text:'A "Minden út Rómába vezet" latin közmondás.', igaz:true, cat:'🧠 Közmondás & Nyelv', exp:'A latin "Omnes viae Romam ducunt" a Római Birodalom úthálózatára utal.' },
  { text:'A magyar az egyetlen finnugor nyelv Európában.', igaz:false, cat:'🧠 Közmondás & Nyelv', exp:'A finn, észt és több kisebb nyelv (pl. számi) is finnugor Európában.' },
  { text:'Az esperanto a legelterjedtebb mesterséges nyelv.', igaz:true, cat:'🧠 Közmondás & Nyelv', exp:'Az eszperantónak kb. 1-2 millió aktív beszélője van világszerte.' },
  { text:'A magyar ABC-ben 44 betű van.', igaz:true, cat:'🧠 Közmondás & Nyelv', exp:'A magyar ábécé 44 betűből áll.' },
  { text:'A legtöbb szót az angol nyelv tartalmazza.', igaz:true, cat:'🧠 Közmondás & Nyelv', exp:'Az angol szótárakban ~170 000 aktív szó van, ez a legtöbb.' },
  { text:'A mandarin a világ legtöbbet beszélt anyanyelve.', igaz:true, cat:'🧠 Közmondás & Nyelv', exp:'A mandarin kínainak kb. 900 millió anyanyelvi beszélője van.' },
  { text:'A japánban nincs ábécé.', igaz:false, cat:'🧠 Közmondás & Nyelv', exp:'A japánban két szótagírás (hiragana, katakana) és kanji karakterek vannak.' },
  { text:'A "robot" szó cseh eredetű.', igaz:true, cat:'🧠 Közmondás & Nyelv', exp:'Karel Čapek cseh író 1920-ban alkotta a "robot" szót (robota = munka).' },
  { text:'A latin holt nyelv, amit senki sem beszél.', igaz:false, cat:'🧠 Közmondás & Nyelv', exp:'A Vatikánban a latin hivatalos nyelv, és vannak anyanyelvi szintű latin tudósok.' },
  { text:'A "kvark" szót James Joyce regényéből vette a fizika.', igaz:true, cat:'🧠 Közmondás & Nyelv', exp:'Murray Gell-Mann Joyce Finnegans Wake-jéből vette a "Three quarks for Muster Mark" sorból.' },
  { text:'A szanszkrit az egyik legrégebbi ismert írott nyelv.', igaz:true, cat:'🧠 Közmondás & Nyelv', exp:'A szanszkrit irodalmi hagyomány kb. 3500 éves.' },
  { text:'A görög ábécéből ered a latin ábécé.', igaz:true, cat:'🧠 Közmondás & Nyelv', exp:'A latin ábécé az etruszkon keresztül a görög ábécéből fejlődött.' },
  { text:'A magyar "paprika" szó az összes európai nyelvbe átment.', igaz:true, cat:'🧠 Közmondás & Nyelv', exp:'A "paprika" szó magyarból terjedt el az európai nyelvekbe.' },
  { text:'Az arab számokat az arabok találták fel.', igaz:false, cat:'🧠 Közmondás & Nyelv', exp:'Az arab számok Indiából erednek, az arabok közvetítették Európába.' },
  { text:'A braille-írást vakok számára fejlesztette ki alkotója.', igaz:true, cat:'🧠 Közmondás & Nyelv', exp:'Louis Braille maga is vak volt, és vakoknak fejlesztette ki az írásrendszert.' },
  { text:'A HTML programozási nyelv.', igaz:false, cat:'🧠 Közmondás & Nyelv', exp:'A HTML jelölőnyelv (markup language), nem programozási nyelv.' },
  { text:'A kínai írásban kb. 50 000 karakter létezik.', igaz:true, cat:'🧠 Közmondás & Nyelv', exp:'A kínai szótárak kb. 50 000 karaktert tartalmaznak, bár a mindennapi használathoz kb. 2000 elég.' },
  { text:'A Balaton átlagos mélysége 3 méter.', igaz:true, cat:'🌍 Földrajz', exp:'A Balaton átlagmélysége kb. 3.3 méter, legmélyebb pontja ~11 méter.' },
  { text:'Tokió a világ legnépesebb városa.', igaz:true, cat:'🌍 Földrajz', exp:'A Nagy-Tokió agglomeráció ~37 millió fővel a legnépesebb.' },
  { text:'Az Északi-Jeges-tenger édesvizű.', igaz:false, cat:'🌍 Földrajz', exp:'Az Északi-Jeges-tenger sós tengervíz, bár a jég édesvizű.' },
  { text:'A Kaszpi-tenger valójában tó.', igaz:true, cat:'🌍 Földrajz', exp:'A Kaszpi-tenger zárt medencéjű, a világ legnagyobb tava.' },
  { text:'Svájcnak nincs tengeri kijárata.', igaz:true, cat:'🌍 Földrajz', exp:'Svájc teljesen szárazföld által körülvett ország.' },
  { text:'Az Amazonas-medence a világ legnagyobb esőerdeje.', igaz:true, cat:'🌍 Földrajz', exp:'Az Amazonas-medence kb. 5.5 millió km² esőerdőt takar.' },
  { text:'A Tátra Magyarország területén van.', igaz:false, cat:'🌍 Földrajz', exp:'A Tátra Szlovákia és Lengyelország határán húzódik.' },
  { text:'Afrika az egyenlítőt két egyenlő részre osztja.', igaz:false, cat:'🌍 Földrajz', exp:'Az egyenlítő Afrikát kb. 1/3 – 2/3 arányban osztja (több föld délen van).' },
  { text:'A Szuezi-csatorna az Atlanti- és Indiai-óceánt köti össze.', igaz:false, cat:'🌍 Földrajz', exp:'A Szuezi-csatorna a Vörös-tengert és a Földközi-tengert köti össze.' },
  { text:'A Mississippi az USA leghosszabb folyója.', igaz:false, cat:'🌍 Földrajz', exp:'A Missouri folyó néhány km-rel hosszabb a Mississippi-nél.' },
  { text:'Izlandnak nincs hadereje.', igaz:true, cat:'🌍 Földrajz', exp:'Izlandnak nincs hadserege, csak egy kis tengerparti őrség.' },
  { text:'A Hold átmérője a Föld átmérőjének kb. negyede.', igaz:true, cat:'🔬 Tudomány', exp:'Föld: ~12 742 km, Hold: ~3 474 km — kb. 27%-a.' },
  { text:'A neon neonfényt bocsát ki természetesen.', igaz:false, cat:'🔬 Tudomány', exp:'A neon csak elektromos gerjesztésre bocsát ki fényt — természetesen nem világít.' },
  { text:'Az emberi DNS kb. 3 milliárd bázispárból áll.', igaz:true, cat:'🔬 Tudomány', exp:'Az emberi haploid genom kb. 3.2 milliárd bázispárból áll.' },
  { text:'Az elektronok a protonokhoz képest nagyon kicsik.', igaz:true, cat:'🔬 Tudomány', exp:'A proton tömege ~1836-szor nagyobb az elektron tömegénél.' },
  { text:'A kristály üveg valóban tartalmaz ólmot.', igaz:true, cat:'🔬 Tudomány', exp:'A hagyományos kristályüveg ólom-oxidot tartalmaz (ólomkristály).' },
  { text:'A Hold mindig ugyanazt az oldalát mutatja a Föld felé.', igaz:true, cat:'🔬 Tudomány', exp:'A Hold kötött rotációban van a Földdel, mindig ugyanazt az oldalt mutatja.' },
  { text:'A magnézium nem ég el levegőn.', igaz:false, cat:'🔬 Tudomány', exp:'A magnézium élénk fehér lánggal ég levegőn.' },
  { text:'Az összes elem a Napban is megtalálható.', igaz:false, cat:'🔬 Tudomány', exp:'Egyes mesterséges elemek (transzurán elemek) csak rövid ideig léteznek.' },
  { text:'A penészgombából nyerték az első antibiotikumot.', igaz:true, cat:'🔬 Tudomány', exp:'Fleming 1928-ban fedezte fel a penicillint Penicillium penészgombából.' },
  { text:'A fekete lyukak nem rendelkeznek tömeggel.', igaz:false, cat:'🔬 Tudomány', exp:'A fekete lyukak rendkívül nagy tömeggel rendelkeznek.' },
  { text:'A hang nem tud terjedni az űrben.', igaz:true, cat:'🔬 Tudomány', exp:'A hang mechanikai hullám, és vákuumban nem tud terjedni.' },
  { text:'A plasztik az egyik leglassabban bomló emberi alkotás.', igaz:true, cat:'🔬 Tudomány', exp:'A műanyag bomlása több száz évig tart.' },
  { text:'A kobrák meghalnak saját mérgüktől.', igaz:false, cat:'🐾 Állatok', exp:'A kobrák immunisak saját mérgükre.' },
  { text:'A tarantula pókmérgétől az ember meghalhat.', igaz:false, cat:'🐾 Állatok', exp:'A tarantula mérge kellemetlenséget okoz, de embernek nem halálos.' },
  { text:'A varjak felismerik az emberi arcokat.', igaz:true, cat:'🐾 Állatok', exp:'Kutatások igazolták, hogy a varjak képesek egyedi arcokat megkülönböztetni.' },
  { text:'A medvék télálmuk során egyáltalán nem ébrednek fel.', igaz:false, cat:'🐾 Állatok', exp:'A medvék télálma felszínesebb — képesek felébredni, ha zavarják őket.' },
  { text:'A gepárd a világ leggyorsabb szárazföldi állata.', igaz:true, cat:'🐾 Állatok', exp:'A gepárd rövid távokon elérheti a 110-120 km/h sebességet.' },
  { text:'A cápa az egyetlen hal, ami pislogni tud.', igaz:false, cat:'🐾 Állatok', exp:'A cápák nem pislognak, nincs szemhéjuk.' },
  { text:'A teknőspáncél a csigolyákhoz nőtt.', igaz:true, cat:'🐾 Állatok', exp:'A teknős páncélja a gerince és bordái módosulásából alakult ki.' },
  { text:'A flamingó csak egy lábon tud állni.', igaz:false, cat:'🐾 Állatok', exp:'A flamingók mindkét lábukon tudnak állni, de egy lábon is szoktak pihenni.' },
  { text:'Az éjjeli pillék vonzódnak a fényhez.', igaz:true, cat:'🐾 Állatok', exp:'A fototaxis jelenség miatt az éjjeli rovarok a fény felé navigálnak.' },
  { text:'A pingvin a leggyorsabb úszó madár.', igaz:true, cat:'🐾 Állatok', exp:'A kis pingvin akár 36 km/h sebességgel is úszhat.' },
  { text:'A hal memóriája valóban csak 3 másodperc.', igaz:false, cat:'🐾 Állatok', exp:'Kutatások szerint a halak (pl. aranyhal) akár hónapokig emlékeznek dolgokra.' },
  { text:'A farkas a kutya őse.', igaz:true, cat:'🐾 Állatok', exp:'A háziasított kutya a farkas leszármazottja (~15 000 évvel ezelőttről).' },
  { text:'A kakaóbab fáról terem.', igaz:true, cat:'🍔 Étel & Ital', exp:'A kakaóbab a Theobroma cacao fán terem.' },
  { text:'A wasabi legtöbbször tormaból készül.', igaz:true, cat:'🍔 Étel & Ital', exp:'A valódi wasabi drága és ritka — a legtöbb étteremben torma-alapú utánzatot adnak.' },
  { text:'A narancs eredeti színe zöld.', igaz:true, cat:'🍔 Étel & Ital', exp:'A trópusokon a narancs érett állapotban is zöld marad — a hűvösebb klíma teszi narancssárgává.' },
  { text:'A cukor tartósítószerként is funkcionál.', igaz:true, cat:'🍔 Étel & Ital', exp:'A magas cukortartalom megakadályozza a baktériumok szaporodását.' },
  { text:'Az olívaolaj alacsony hőmérsékleten megalszik.', igaz:true, cat:'🍔 Étel & Ital', exp:'Az olívaolaj ~4-10°C körül megalszik, ez normális jelenség.' },
  { text:'A mangó csonthéjas gyümölcs.', igaz:true, cat:'🍔 Étel & Ital', exp:'A mangónak nagy magva van, csonthéjasnak számít.' },
  { text:'A ketchup Amerikából ered.', igaz:false, cat:'🍔 Étel & Ital', exp:'A ketchup ázsiai (kínai/maláj) halszószból fejlődött ki.' },
  { text:'A legjobb minőségű kávét Arabiából importálják.', igaz:false, cat:'🍔 Étel & Ital', exp:'A leghíresebb prémium kávék Etiópiából, Kolumbiából és Jamaicából (Blue Mountain) érkeznek.' },
  { text:'A tojás héja teljesen légmentes.', igaz:false, cat:'🍔 Étel & Ital', exp:'A tojáshéj apró pórusain keresztül gázok is átjuthatnak.' },
  { text:'A barna cukor egészségesebb a fehér cukornál.', igaz:false, cat:'🍔 Étel & Ital', exp:'A barna cukor csak a melaszmaradvány miatt barna — tápértéke alig különbözik.' },
  { text:'A Worcestershire szósz szardellát tartalmaz.', igaz:true, cat:'🍔 Étel & Ital', exp:'A Worcestershire szósz egyik összetevője az erjesztett szardella.' },
  { text:'A szilvapálinka hungarikum.', igaz:true, cat:'🍔 Étel & Ital', exp:'A szilvapálinka (szilvorium) hungarikumnak minősített magyar párlat.' },
  { text:'Az Eiffel-torony Gustave Eiffel tervei alapján épült.', igaz:true, cat:'📜 Történelem', exp:'Gustave Eiffel cége tervezte az 1889-es párizsi világkiállításra.' },
  { text:'A Colosseum az ókori Rómában gladiátorviadaloknak is helyet adott.', igaz:true, cat:'📜 Történelem', exp:'A Colosseum gladiátorharcoknak, állatküzdelmeknek és más látványosságoknak adott helyet.' },
  { text:'Az inka birodalom az európaiak érkezésekor a világ legnagyobb birodalma volt.', igaz:false, cat:'📜 Történelem', exp:'Az inka birodalom hatalmas volt Dél-Amerikában, de az Oszmán Birodalom nagyobb volt.' },
  { text:'Galileo Galilei a teleszkópot találta fel.', igaz:false, cat:'📜 Történelem', exp:'A teleszkópot Hans Lippershey találta fel 1608-ban — Galilei fejlesztette tovább.' },
  { text:'A kerék az emberiség egyik legfontosabb találmánya.', igaz:true, cat:'📜 Történelem', exp:'A kereket kb. 3500 BC-ben találták fel Mezopotámiában.' },
  { text:'Az Ottomán Birodalom 600 évig állt fenn.', igaz:true, cat:'📜 Történelem', exp:'Az Oszmán Birodalom 1299-től 1922-ig tartott, kb. 623 évig.' },
  { text:'A papírt az egyiptomiak találták fel.', igaz:false, cat:'📜 Történelem', exp:'A papírt a kínaiak találták fel kb. Kr.u. 100 körül, az egyiptomiak papiruszt használtak.' },
  { text:'Az ókori Maya civilizáció kiterjedt naptárrendszert fejlesztett ki.', igaz:true, cat:'📜 Történelem', exp:'A Maya naptár rendkívül pontos volt és több párhuzamos ciklust tartalmazott.' },
  { text:'A gumiabroncsot a 20. században találták fel.', igaz:false, cat:'📜 Történelem', exp:'Charles Goodyear 1844-ben szabadalmaztatta a vulkanizált gumit.' },
  { text:'A szteroidokat sportban való alkalmazásra fejlesztették ki.', igaz:false, cat:'📜 Történelem', exp:'A szteroidokat orvosi célokra fejlesztették ki, pl. gyulladás kezelésére.' },
  { text:'A viking hajók mediterrán stílusban épültek.', igaz:false, cat:'📜 Történelem', exp:'A viking longshipek egyedülállóan sekély merülésű, gyors hajók voltak.' },
  { text:'A nyomtatást Gutenberg találta fel.', igaz:false, cat:'📜 Történelem', exp:'A nyomtatást a kínaiak találták fel — Gutenberg a mozgatható betűs nyomtatást fejlesztette ki Európában.' },
  { text:'Leonardo da Vinci bal kézzel írt.', igaz:true, cat:'📜 Történelem', exp:'Leonardo ambidexternek tartják, de elsősorban bal kézzel írt, tükörírással.' },
  { text:'Az ókori olimpián nem volt síverseny.', igaz:true, cat:'📜 Történelem', exp:'Az ókori olimpiát nyáron tartották, a téli sportok nem szerepeltek.' },
  { text:'A Coldplay brit együttes.', igaz:true, cat:'🎬 Film & Zene', exp:'A Coldplay 1996-ban alakult Londonban.' },
  { text:'Az Oscart mindig az Academy of Motion Picture Arts and Sciences adja.', igaz:true, cat:'🎬 Film & Zene', exp:'Az Oscar-díjat az Amerikai Filmakadémia adományozza.' },
  { text:'A The Dark Knight (2008) Heath Ledger utolsó filmje volt.', igaz:false, cat:'🎬 Film & Zene', exp:'A The Imaginarium of Doctor Parnassus volt az utolsó filmje, amit halála után fejeztek be.' },
  { text:'A Spotify 2006-ban indult el.', igaz:false, cat:'🎬 Film & Zene', exp:'A Spotify 2008-ban indult Svédországban.' },
  { text:'A Toy Story volt az első teljes egészében számítógéppel animált játékfilm.', igaz:true, cat:'🎬 Film & Zene', exp:'A Pixar 1995-ös Toy Story az első CGI nagyjátékfilm.' },
  { text:'A U2 ír rock együttes.', igaz:true, cat:'🎬 Film & Zene', exp:'A U2 1976-ban alakult Dublinban, Írországban.' },
  { text:'A YouTube-ot a Google alapította.', igaz:false, cat:'🎬 Film & Zene', exp:'A YouTube-ot Chad Hurley, Steve Chen és Jawed Karim alapította 2005-ben, a Google 2006-ban vette meg.' },
  { text:'A világ legértékesebb festménye a Mona Lisa.', igaz:true, cat:'🎬 Film & Zene', exp:'A Mona Lisa biztosítási értéke a legtöbb becslés szerint a legmagasabb.' },
  { text:'A "Bohemian Rhapsody" a Queen legismertebb dala.', igaz:true, cat:'🎬 Film & Zene', exp:'A Bohemian Rhapsody a legtöbbet streamelt klasszikus rock dal.' },
  { text:'A Netflix 1997-ben postai DVD kölcsönzőként indult.', igaz:true, cat:'🎬 Film & Zene', exp:'A Netflix eredetileg DVD-ket küldött postán, 2007-ben váltott streamingre.' },
  { text:'Adele brit énekesnő.', igaz:true, cat:'🎬 Film & Zene', exp:'Adele Adkins 1988-ban született Londonban.' },
  { text:'A Minecraft 2011-ben jelent meg teljes verzióban.', igaz:true, cat:'🎬 Film & Zene', exp:'A Minecraft 2011. november 18-án jelent meg 1.0 verzióként.' },
  { text:'A Simpsons az 1990-es évek óta megy folyamatosan.', igaz:true, cat:'🎬 Film & Zene', exp:'A Simpsons 1989 óta megy — a leghosszabban futó animációs sorozat.' },
  { text:'A Fortnite és a PUBG azonos cég terméke.', igaz:false, cat:'🎬 Film & Zene', exp:'A Fortnite-ot az Epic Games, a PUBG-ot a PUBG Corporation (Krafton) fejlesztette.' },
  { text:'A Manchester City és a Manchester United azonos stadionban játszik.', igaz:false, cat:'⚽ Sport', exp:'A City az Etihad Stadionban, az United az Old Traffordban játszik.' },
  { text:'A Forma-1-ben összesen 20 autó indul egy szezonban.', igaz:false, cat:'⚽ Sport', exp:'Általában 20 autó (10 csapat × 2 versenyző) indul egy szezonban.' },
  { text:'Messi argentin labdarúgó.', igaz:true, cat:'⚽ Sport', exp:'Lionel Messi Rosarióban született 1987-ben, argentin állampolgár.' },
  { text:'A Wimbledon tenisztorna mindig júniusban vagy júliusban zajlik.', igaz:true, cat:'⚽ Sport', exp:'A Wimbledont hagyományosan június végén és július elején rendezik.' },
  { text:'A baseballt Kanadában találták fel.', igaz:false, cat:'⚽ Sport', exp:'A baseball az Egyesült Államokban fejlődött ki a 19. században.' },
  { text:'A Tour de France 21 szakaszból áll.', igaz:true, cat:'⚽ Sport', exp:'A Tour de France általában 21 napi szakaszból áll.' },
  { text:'A jégkorong Kanada nemzeti sportja.', igaz:true, cat:'⚽ Sport', exp:'A jégkorong Kanada egyik nemzeti sportja, a lakrossz mellett.' },
  { text:'A vívás olimpiai sport.', igaz:true, cat:'⚽ Sport', exp:'A vívás az 1896-os athéni olimpia óta szerepel a programban.' },
  { text:'Ronaldo és Messi sosem játszottak ugyanabban a csapatban.', igaz:true, cat:'⚽ Sport', exp:'Cristiano Ronaldo és Lionel Messi egész pályafutásuk alatt riválisok maradtak.' },
  { text:'A snooker biliárddal azonos sport.', igaz:false, cat:'⚽ Sport', exp:'A snooker és a billiárd különböző szabályú, különböző asztalon játszott sportok.' },
  { text:'A szurkolást az olimpiai programból soha nem zárták ki.', igaz:false, cat:'⚽ Sport', exp:'A szurkálás (tug of war) és más sportok már kikerültek az olimpiai programból.' },
  { text:'A kézilabda olimpiai sport.', igaz:true, cat:'⚽ Sport', exp:'A kézilabda 1972 óta szerepel az olimpia programjában.' },
  { text:'A gyorskorcsolyázás és a műkorcsolyázás azonos sport.', igaz:false, cat:'⚽ Sport', exp:'A gyorskorcsolya és a műkorcsolya különböző cipőt, technikát és versenyszabályt használ.' },
  { text:'Michael Jordan 6 NBA-bajnoki gyűrűt nyert.', igaz:true, cat:'⚽ Sport', exp:'Jordan a Chicago Bullsszal 6 bajnoki gyűrűt szerzett (1991-93, 1996-98).' },
  { text:'A vízilabda vb-t Magyarország többször is megnyerte.', igaz:true, cat:'⚽ Sport', exp:'Magyarország a világ egyik legsikeresebb vízilabdanemzete.' },
  { text:'Az emberi agy csak 10%-át használja egyszerre.', igaz:false, cat:'🫀 Emberi test', exp:'Ez egy tévhit — az agy szinte minden területe aktív valamilyen szinten.' },
  { text:'A tüsszentés szeme zárásával jár.', igaz:true, cat:'🫀 Emberi test', exp:'A tüsszentés reflexes szemmozgással, automatikus szemcsukással jár.' },
  { text:'Az emberi test naponta kb. 2 millió vörösvérsejtet termel.', igaz:false, cat:'🫀 Emberi test', exp:'A test naponta kb. 200 milliárd vörösvérsejtet termel.' },
  { text:'A köhögés gyorsabb, mint a tüsszentés.', igaz:false, cat:'🫀 Emberi test', exp:'A tüsszentés ~160 km/h, a köhögés ~80-160 km/h — hasonlóak, de a tüsszentés általában gyorsabb.' },
  { text:'Az alvás alatt az ember nem produkál nyálat.', igaz:false, cat:'🫀 Emberi test', exp:'A nyáltermelés csökken alváskor, de nem áll meg teljesen.' },
  { text:'Az emberi fül három apró csontocskát tartalmaz.', igaz:true, cat:'🫀 Emberi test', exp:'A kalapács, az üllő és a kengyel a három hallócsontocska.' },
  { text:'A bőr folyamatosan megújul kb. minden 27 napban.', igaz:true, cat:'🫀 Emberi test', exp:'A bőr külső rétege kb. 4 hetente teljesen kicserélődik.' },
  { text:'A hajszál erősebb az acélnál.', igaz:false, cat:'🫀 Emberi test', exp:'Az acél szakítószilárdsága jóval nagyobb, mint a hajé — tömegre vetítve hasonló.' },
  { text:'Az emberi láb kb. 26 csontból áll.', igaz:true, cat:'🫀 Emberi test', exp:'A lábban 26 csont, 33 ízület és több mint 100 ín és szalag van.' },
  { text:'A szív percenként kb. 5 liter vért pumpál.', igaz:true, cat:'🫀 Emberi test', exp:'Nyugalmi állapotban a szív ~5 liter vért kering át percenként.' },
  { text:'A térd az emberi test legnagyobb ízülete.', igaz:true, cat:'🫀 Emberi test', exp:'A térd a legnagyobb és egyik legbonyolultabb ízület az emberi testben.' },
  { text:'A köröm és a haj ugyanolyan anyagból áll.', igaz:true, cat:'🫀 Emberi test', exp:'Mindkettő keratinból áll, ez egy szerkezeti fehérje.' },
  { text:'Az emésztés csak a gyomorban zajlik.', igaz:false, cat:'🫀 Emberi test', exp:'Az emésztés a szájban kezdődik és a vékonybélben fejeződik be.' },
  { text:'Az emberi testnek szüksége van C-vitaminra, mert nem tudja előállítani.', igaz:true, cat:'🫀 Emberi test', exp:'Az ember elveszítette a C-vitamin belső szintézisének képességét.' },
  { text:'A pajzsmirigy a has alsó részén helyezkedik el.', igaz:false, cat:'🫀 Emberi test', exp:'A pajzsmirigy a nyakban, a légcső előtt helyezkedik el.' },
  { text:'Magyarország 1000-ben alapítva lett, i.sz.', igaz:true, cat:'📜 Történelem', exp:'István király i.sz. 1000-ben vette fel a koronát és alapította meg a keresztény Magyar Királyságot.' },
  { text:'Az USA-t 1776-ban alapítottak.', igaz:true, cat:'📜 Történelem', exp:'A Függetlenségi nyilatkozatot 1776. július 4-én fogadták el.' },
  { text:'Gandhi erőszakos eszközökkel harcolt a brit uralom ellen.', igaz:false, cat:'📜 Történelem', exp:'Gandhi a passzív ellenállás és polgári engedetlenség elveit vallotta.' },
  { text:'A holokauszt során kb. 6 millió zsidót gyilkoltak meg.', igaz:true, cat:'📜 Történelem', exp:'A náci Németország kb. 6 millió zsidót és több millió más embert gyilkolt meg.' },
  { text:'Az ókori egyiptomiak piramisokat építettek temetkezési célra.', igaz:true, cat:'📜 Történelem', exp:'A piramisok fáraók sírhelyi épületek voltak.' },
  { text:'A Szovjetunió 1991-ben szűnt meg.', igaz:true, cat:'📜 Történelem', exp:'A Szovjetunió 1991. december 25-én hivatalosan feloszlott.' },
  { text:'A Fekete-halál (pestis) a 14. században söpört végig Európán.', igaz:true, cat:'📜 Történelem', exp:'Az 1347-1351-es pestisjárvány Európa népességének egyharmadát pusztította el.' },
  { text:'A spanyol polgárháborúban Franco nyert.', igaz:true, cat:'📜 Történelem', exp:'Francisco Franco 1939-ben szerezte meg a hatalmat Spanyolországban.' },
  { text:'A kínai fal a Ming-dinasztia idején épült legnagyobb részben.', igaz:true, cat:'📜 Történelem', exp:'A mai formájában legtöbb fal a Ming-dinasztia (1368-1644) idején épültek.' },
  { text:'Az emberi test hőmérséklete 37°C körül normális.', igaz:true, cat:'🫀 Emberi test', exp:'A normál testhőmérséklet 36.1-37.2°C között van.' },
  { text:'A vér kék, amíg az erekben van.', igaz:false, cat:'🫀 Emberi test', exp:'A vér az erekben is piros — az oxigénszegény vér sötétebb piros, nem kék.' },
  { text:'A hasnyálmirigy az emésztésben és az inzulintermelésben is részt vesz.', igaz:true, cat:'🫀 Emberi test', exp:'A hasnyálmirigy emésztőenzimeket és inzulint is termel.' },
  { text:'Az üstökösök a Naprendszeren kívülről érkeznek.', igaz:false, cat:'🔬 Tudomány', exp:'A legtöbb üstökös az Oort-felhőből vagy a Kuiper-övből ered, ami a Naprendszer részei.' },
  { text:'A tenger vize nem fagyhat meg.', igaz:false, cat:'🔬 Tudomány', exp:'A tengervíz kb. -1.8°C-on fagy meg a só miatt.' },
  { text:'A szén számos allotrop formában létezik (pl. gyémánt, grafit).', igaz:true, cat:'🔬 Tudomány', exp:'A szén allotropjai: grafit, gyémánt, fulleren, grafén, szénnanocső.' },
  { text:'A neutroncsillag sűrűsége nagyobb, mint a fehér törpéé.', igaz:true, cat:'🔬 Tudomány', exp:'A neutroncsillagnál sűrűbb csak a fekete lyuk szingularitása.' },
  { text:'A közönséges só (NaCl) két mérgező elemből áll.', igaz:true, cat:'🔬 Tudomány', exp:'A nátrium (tűzveszélyes fém) és a klór (mérgező gáz) együtt konyhasót alkot.' },
  { text:'A Naprendszer kb. 4.6 milliárd éves.', igaz:true, cat:'🔬 Tudomány', exp:'A legkorábbi meteoritmintákból mérve a Naprendszer kora kb. 4.568 milliárd év.' },
  { text:'Az Antarktika teli van szénhidrogénnel.', igaz:true, cat:'🔬 Tudomány', exp:'Az Antarktika jege alatt kiterjedt olaj- és gázkészletek sejthetők.' },
  { text:'A röntgensugárzást véletlenül fedezték fel.', igaz:true, cat:'🔬 Tudomány', exp:'Wilhelm Röntgen 1895-ben véletlenül fedezte fel a röntgensugárzást.' },
  { text:'A vírus élő szervezet.', igaz:false, cat:'🔬 Tudomány', exp:'A vírusok nem rendelkeznek sejtszerkezettel, nem tekintjük őket élő szervezetnek.' },
  { text:'A természetes szelekció fogalmát Darwin vezette be.', igaz:true, cat:'🔬 Tudomány', exp:'Darwin 1859-ben publikálta "A fajok eredete" c. művét a természetes szelekció elvével.' },
  { text:'A Tesla nem volt villanymérnök, csak üzletember.', igaz:false, cat:'🔬 Tudomány', exp:'Nikola Tesla zseniális feltaláló és mérnök volt, nem csak üzletember.' },
  { text:'A görög mitológiában Zeusz a mennydörgés istene.', igaz:true, cat:'📜 Történelem', exp:'Zeusz a görög mitológia főistene, az ég és a mennydörgés ura.' },
  { text:'A középkorban azt hitték, a Föld lapos.', igaz:false, cat:'📜 Történelem', exp:'A középkori tudósok is tudták, hogy a Föld gömbölyű — az ókori görögök óta.' },
  { text:'A feudalizmus a középkori Európában volt elterjedt.', igaz:true, cat:'📜 Történelem', exp:'A feudális rendszer a középkori Európa jellemző társadalmi-gazdasági rendszere volt.' },
  { text:'A 30 éves háború (1618-1648) valóban 30 évig tartott.', igaz:true, cat:'📜 Történelem', exp:'A 30 éves háború pontosan 1618-tól 1648-ig zajlott.' },
  { text:'Kopernikusz azt hirdette, a Föld áll a Naprendszer középpontjában.', igaz:false, cat:'📜 Történelem', exp:'Kopernikusz a heliocentrikus (Nap-középpontú) rendszert hirdette.' },
  { text:'A focilabda 32 panelből áll hagyományosan.', igaz:true, cat:'⚽ Sport', exp:'A klasszikus labda 20 fehér hatszögből és 12 fekete ötszögből áll, összesen 32 panel.' },
  { text:'Az NBA kosárlabdában nincsenek nők.', igaz:true, cat:'⚽ Sport', exp:'Az NBA csak férfi liga — a WNBA a women\'s verzió.' },
  { text:'A pingpongot table tennis-nek is hívják.', igaz:true, cat:'⚽ Sport', exp:'Az asztalitenisz és a pingpong ugyanaz a sport, csak más nevekkel.' },
  { text:'A birkózás az egyik legrégebbi olimpiai sport.', igaz:true, cat:'⚽ Sport', exp:'A birkózás az első 776 BC-es olimpia óta szerepel a programban.' },
  { text:'A Tour de France-t mindig kerékpározva teszik meg.', igaz:true, cat:'⚽ Sport', exp:'A Tour de France egy kerékpározó verseny — kizárólag kerékpárral.' },
  { text:'A röplabda hálója alacsonyabb, mint a teniszé.', igaz:false, cat:'⚽ Sport', exp:'A röplabda háló 2.43 m (férfi), a tenisz háló 0.914 m a középen — tehát a röplabda magasabb.' },
  { text:'A Magyar Nagydíjat (F1) Mogyoródon rendezik.', igaz:true, cat:'⚽ Sport', exp:'A Hungaroring Mogyoródon található, ahol a Magyar Nagydíjat tartják.' },
  { text:'A "hat" a teniszben 6 nyert gemet jelent.', igaz:false, cat:'⚽ Sport', exp:'A teniszben egy szettet 6 gemmel lehet megnyerni (de lehet több, ha van egyenlítés).' },
  { text:'A maratoni futást az 1896-os olimpián vezették be.', igaz:true, cat:'⚽ Sport', exp:'A modern maraton az 1896-os athéni olimpián szerepelt először.' },
  { text:'Az asztalitenisz 1900 körül Angliában fejlődött ki.', igaz:true, cat:'⚽ Sport', exp:'Az asztaliteniszt (pingpong) Angliában fejlesztették ki a 19-20. század fordulóján.' },
  { text:'A sakkban a vezér (királynő) a leghatalmasabb bábu.', igaz:true, cat:'⚽ Sport', exp:'A vezér léphet akármennyi mezőt vízszintesen, függőlegesen és átlósan.' },
  { text:'A kosárlabdapályán pontosan 10 játékos lehet egyszerre.', igaz:true, cat:'⚽ Sport', exp:'Csapatonként 5 fő játszik, összesen 10 játékos van a pályán.' },
  { text:'A Grand Slam teniszben négy tornát foglal magában.', igaz:true, cat:'⚽ Sport', exp:'Australian Open, Roland Garros, Wimbledon és US Open alkotja a Grand Slamet.' },
  { text:'A tigris úszni tud.', igaz:true, cat:'🐾 Állatok', exp:'A tigrisek kiváló úszók, és szeretnek a vízben tartózkodni.' },
  { text:'A szúnyog az emberiség számára legtöbb halálos áldozatot okozó állat.', igaz:true, cat:'🐾 Állatok', exp:'A szúnyog betegségei (malária, dengue stb.) évente több millió embert ölnek meg.' },
  { text:'A kolibri az egyetlen madár, amely visszafelé is tud repülni.', igaz:true, cat:'🐾 Állatok', exp:'A kolibri szárnyai speciális mozgással teszik lehetővé a visszafelé repülést.' },
  { text:'A krokodil emésztőrendszere savban oldja fel a csontokat.', igaz:true, cat:'🐾 Állatok', exp:'A krokodil gyomorsava rendkívül erős, még csontokat is képes feloldani.' },
  { text:'A boa constrictor megfojtja áldozatát.', igaz:true, cat:'🐾 Állatok', exp:'A boa constrictor összeszorítással fullaszt meg, nem méreggel öl.' },
  { text:'A gorilla nem tud úszni.', igaz:true, cat:'🐾 Állatok', exp:'A gorillák rettegnek a víztől és nem tudnak úszni.' },
  { text:'A pávián nem majom, hanem majomféle.', igaz:false, cat:'🐾 Állatok', exp:'A pávián valódi majom, az óvilági majmok csoportjába tartozik.' },
  { text:'A kenguru születéskor körülbelül 1 grammos.', igaz:true, cat:'🐾 Állatok', exp:'A nagy vörös kenguru kölyke születéskor kb. 0.8 grammos és 2.5 cm hosszú.' },
  { text:'A rovarok vére piros.', igaz:false, cat:'🐾 Állatok', exp:'A rovarok vérnedve (hemolimfa) általában sárgas vagy zöldes, nem tartalmaz hemoglobint.' },
  { text:'Az elefánt terhessége 22 hónapig tart.', igaz:true, cat:'🐾 Állatok', exp:'Az afrikai elefánt terhessége kb. 22 hónap, ez a leghosszabb a szárazföldi emlősök között.' },
  { text:'A kameleon azért változtatja a színét, hogy elrejtőzön.', igaz:false, cat:'🐾 Állatok', exp:'A kameleon elsősorban kommunikációra, hangulatjelzésre és hőszabályozásra változtat színt.' },
  { text:'A vombat kocka alakú ürüléket produkál.', igaz:true, cat:'🐾 Állatok', exp:'A vombat egyedülálló az állatvilágban azzal, hogy kocka formájú ürüléket termel.' },
  { text:'A disznók a természetben tisztátlanok.', igaz:false, cat:'🐾 Állatok', exp:'A disznók természetben tiszaták és nem hemperednek szívesen a sárban, ha elég hűvös.' },
  { text:'A sas a világ leggyorsabb madara.', igaz:false, cat:'🐾 Állatok', exp:'A vándorsólyom a leggyorsabb madár (~389 km/h zuhanórepülésben).' },
  { text:'A hal a száraz levegőn percek alatt meghal.', igaz:false, cat:'🐾 Állatok', exp:'Egyes halfajok (pl. tüdőhal, vándorhal) órákon át életben maradhatnak szárazon.' },
  { text:'A bálna cetek rendjébe tartozik.', igaz:true, cat:'🐾 Állatok', exp:'A bálna cetféle (Cetacea), emlős állat.' },
  { text:'Az egér jobb memóriával rendelkezik, mint a hal.', igaz:true, cat:'🐾 Állatok', exp:'Az egér összetett labirintusokban is képes tájékozódni, és hosszú távú memóriája van.' },
  { text:'A gin és a vodka azonos alapanyagból készül.', igaz:false, cat:'🍔 Étel & Ital', exp:'A vodka lehet gabona- vagy burgonyaalapú, a gin gabonaalapú szeszből készül juniperbokállyal ízesítve.' },
  { text:'A tejes kávé (latte) több koffeint tartalmaz, mint az eszpresszó.', igaz:false, cat:'🍔 Étel & Ital', exp:'Az eszpresszó koncentráltabb koffeint tartalmaz, bár a latte több folyadék.' },
  { text:'A friss tészta kevesebb ideig főzzük, mint a száraz.', igaz:true, cat:'🍔 Étel & Ital', exp:'A friss tészta már 2-3 perc alatt al dente, a száraz 8-12 percet igényel.' },
  { text:'A fehér csoki valójában nem csokoládé.', igaz:true, cat:'🍔 Étel & Ital', exp:'A fehér csoki kakaóvajat tartalmaz, de kakaópasztát nem, ezért nem igazi csokoládé.' },
  { text:'A chili erős paprika egy külön növényfaj.', igaz:false, cat:'🍔 Étel & Ital', exp:'A chili és a paprika ugyanannak a fajnak (Capsicum) fajtái.' },
  { text:'A sushi rizzsel együtt fogyasztják.', igaz:true, cat:'🍔 Étel & Ital', exp:'A sushi definíció szerint fűszerezett (ecetes-cukros) rizzsel készül.' },
  { text:'A champagne mindig édes.', igaz:false, cat:'🍔 Étel & Ital', exp:'A champagne lehet Brut (száraz), demi-sec (félszáraz) és más variáns is.' },
  { text:'A gyömbér gyökér.', igaz:true, cat:'🍔 Étel & Ital', exp:'Pontosabban rizóma (szárgyökér), de a köznyelvben gyökérként ismert.' },
  { text:'A búzacsíra gluténtartalmú.', igaz:true, cat:'🍔 Étel & Ital', exp:'A búzacsíra búzából ered, ezért tartalmaz glutént.' },
  { text:'A kókuszolaj szobahőmérsékleten folyékony.', igaz:false, cat:'🍔 Étel & Ital', exp:'A kókuszolaj ~24°C alatt szilárd, felett folyékony.' },
  { text:'A füge virágzik, de a virágja belül van.', igaz:true, cat:'🍔 Étel & Ital', exp:'A fügegyümölcs valójában egy belülről nyíló virágzat (syconium).' },
  { text:'A szójaszósz Japánból ered.', igaz:false, cat:'🍔 Étel & Ital', exp:'A szójaszósz Kínából ered, de Japánban is évszázadok óta gyártják.' },
  { text:'A nyár végén szüretelt szőlőből jobb bor lesz.', igaz:false, cat:'🍔 Étel & Ital', exp:'A szüret időzítése évtől és fajtától is függ — nem mindig a nyár vége a legjobb.' },
  { text:'A számok nullától kezdődnek a számítástechnikában.', igaz:true, cat:'🧠 Közmondás & Nyelv', exp:'A legtöbb programozási nyelv 0-tól indexel (pl. tömbök első eleme a 0. index).' },
  { text:'A "selfie" szó az Oxford-szótárban szerepel.', igaz:true, cat:'🧠 Közmondás & Nyelv', exp:'A "selfie" szót 2013-ban vette fel az Oxford-szótár.' },
  { text:'A "karantén" szó olasz eredetű.', igaz:true, cat:'🧠 Közmondás & Nyelv', exp:'A "quarantina" (negyven nap) szóból ered, a velencei pestiselőírásokból.' },
  { text:'A Pitagorasz-tétel kizárólag derékszögű háromszögekre vonatkozik.', igaz:true, cat:'🧠 Közmondás & Nyelv', exp:'A² + B² = C² csak derékszögű háromszögre igaz, ahol C az átfogó.' },
  { text:'A Magyar Tudományos Akadémiát Széchenyi István alapította.', igaz:true, cat:'🧠 Közmondás & Nyelv', exp:'Széchenyi 1825-ben ajánlotta fel egyévi jövedelmét a Magyar Tudós Társaság alapítására.' },
  { text:'A "buli" szó angol jövevényszó a magyarban.', igaz:true, cat:'🧠 Közmondás & Nyelv', exp:'A "buli" a party/ball angol szóból ered.' },
  { text:'A Fibonacci-sorozatban minden szám az előző kettő szorzata.', igaz:false, cat:'🧠 Közmondás & Nyelv', exp:'A Fibonacci-sorozatban minden szám az előző kettő összege (1, 1, 2, 3, 5, 8...).' },
  { text:'A szó "algoritmus" arabból ered.', igaz:true, cat:'🧠 Közmondás & Nyelv', exp:'Al-Hvárizmi perzsa matematikus nevéből ered (al-Khwarizmi → algoritmus).' },
  { text:'A magyar "kocsi" szó más nyelvekbe is átment.', igaz:true, cat:'🧠 Közmondás & Nyelv', exp:'A "kocsi" (Kocs faluból) angolul "coach", franciául "coche" stb.' },
  { text:'Az ábécé sorrendje véletlenszerű.', igaz:true, cat:'🧠 Közmondás & Nyelv', exp:'A latin ábécé betűinek sorrendje nem a hangzók kapcsolatán, hanem hagyományon alapul.' },
  { text:'A "szoftver" szó magyarítása a "puhaszer" lett volna.', igaz:false, cat:'🧠 Közmondás & Nyelv', exp:'A szoftver magyarítása "szoftver" maradt a köznyelvi használatban.' },
  { text:'A pi (π) irracionális szám.', igaz:true, cat:'🧠 Közmondás & Nyelv', exp:'A π nem írható fel két egész szám hányadosaként, és tizedes jegyei nem ismétlődnek.' },
  { text:'Az "okay" rövidítés az "oll korrect" humoros helyesírásából ered.', igaz:true, cat:'🧠 Közmondás & Nyelv', exp:'Az OK az 1800-as évek bostoni divatjából ered, ahol tréfásan "oll korrect" rövidítése volt.' },
];
'''

with open('index.html', 'r', encoding='utf-8') as f:
    content = f.read()

OLD_START = 'const IGAZ_HAMIS = ['
old_start_idx = content.index(OLD_START)
old_end_idx = content.index('];', old_start_idx) + 2

old_block = content[old_start_idx:old_end_idx]
assert OLD_START in old_block, 'IGAZ_HAMIS start not found'

new_content = content[:old_start_idx] + NEW_IGAZ_HAMIS.strip() + content[old_end_idx:]

# Version bump
assert 'Verzió 5.66' in new_content
new_content = new_content.replace('Verzió 5.66', 'Verzió 5.67', 1)

with open('index.html', 'w', encoding='utf-8') as f:
    f.write(new_content)

print('OK — IGAZ_HAMIS updated to 500 questions, version bumped to 5.67')
