with open('index.html', 'r', encoding='utf-8') as f:
    content = f.read()

NEW_CELEBS = """const KIVAGYOK_CELEBS = [
  { name:'Albert Einstein',      info:'1879–1955 · Fizikus',              img:'https://upload.wikimedia.org/wikipedia/commons/d/d3/Albert_Einstein_Head.jpg' },
  { name:'Barack Obama',         info:'1961– · Politikus',                img:'https://upload.wikimedia.org/wikipedia/commons/8/8d/President_Barack_Obama.jpg' },
  { name:'Elon Musk',            info:'1971– · Vállalkozó',               img:'https://upload.wikimedia.org/wikipedia/commons/3/34/Elon_Musk_Royal_Society_%28crop2%29.jpg' },
  { name:'Marilyn Monroe',       info:'1926–1962 · Színésznő',            img:'https://upload.wikimedia.org/wikipedia/commons/1/1e/Marilyn_Monroe_in_1952.jpg' },
  { name:'Bob Marley',           info:'1945–1981 · Zenész',               img:'https://upload.wikimedia.org/wikipedia/commons/b/b2/Bob_Marley_Concert_23071978_01_%28cropped%29.jpg' },
  { name:'Freddie Mercury',      info:'1946–1991 · Zenész',               img:'https://upload.wikimedia.org/wikipedia/commons/9/9a/Freddie_Mercury_performing_in_New_Haven%2C_CT%2C_November_1977.jpg' },
  { name:'Michael Jordan',       info:'1963– · Kosárlabdázó',             img:'https://upload.wikimedia.org/wikipedia/commons/a/ae/Michael_Jordan_in_2014.jpg' },
  { name:'Leonardo da Vinci',    info:'1452–1519 · Festő, feltaláló',     img:'https://upload.wikimedia.org/wikipedia/commons/b/ba/Leonardo_self.jpg' },
  { name:'Napoleon Bonaparte',   info:'1769–1821 · Hadvezér',             img:'https://upload.wikimedia.org/wikipedia/commons/b/b5/Jacques-Louis_David_-_The_Emperor_Napoleon_in_His_Study_at_the_Tuileries_-_Google_Art_Project_2.jpg' },
  { name:'Muhammad Ali',         info:'1942–2016 · Bokszoló',             img:'https://upload.wikimedia.org/wikipedia/commons/8/89/Muhammad_Ali_NYWTS.jpg' },
  { name:'Mahatma Gandhi',       info:'1869–1948 · Politikus',            img:'https://upload.wikimedia.org/wikipedia/commons/7/7a/Mahatma-Gandhi%2C_studio%2C_1931.jpg' },
  { name:'Charles Darwin',       info:'1809–1882 · Természettudós',       img:'https://upload.wikimedia.org/wikipedia/commons/a/ae/Charles_Darwin_seated_crop.jpg' },
  { name:'Vincent van Gogh',     info:'1853–1890 · Festő',                img:'https://upload.wikimedia.org/wikipedia/commons/b/b3/Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project_%28454045%29.jpg' },
  { name:'Isaac Newton',         info:'1643–1727 · Fizikus, matematikus', img:'https://upload.wikimedia.org/wikipedia/commons/3/3b/Portrait_of_Sir_Isaac_Newton%2C_1689.jpg' },
  { name:'Nikola Tesla',         info:'1856–1943 · Feltaláló',            img:'https://upload.wikimedia.org/wikipedia/commons/d/d4/N.Tesla.JPG' },
  { name:'Stephen Hawking',      info:'1942–2018 · Fizikus',              img:'https://upload.wikimedia.org/wikipedia/commons/e/eb/Stephen_Hawking.StarChild.jpg' },
  { name:'Walt Disney',          info:'1901–1966 · Animátor, producer',   img:'https://upload.wikimedia.org/wikipedia/commons/d/df/Walt_Disney_1946.JPG' },
  { name:'Elvis Presley',        info:'1935–1977 · Énekes',               img:'https://upload.wikimedia.org/wikipedia/commons/a/a1/Elvis_Presley_promoting_Jailhouse_Rock.jpg' },
  { name:'Audrey Hepburn',       info:'1929–1993 · Színésznő',            img:'https://upload.wikimedia.org/wikipedia/commons/0/0b/Audrey_Hepburn_1956.jpg' },
  { name:'Leonardo DiCaprio',    info:'1974– · Színész',                  img:'https://upload.wikimedia.org/wikipedia/commons/2/25/Leonardo_DiCaprio_2010.jpg' },
  { name:'Angelina Jolie',       info:'1975– · Színésznő',                img:'https://upload.wikimedia.org/wikipedia/commons/a/ad/Angelina_Jolie_2_June_2014_%28cropped%29.jpg' },
  { name:'Brad Pitt',            info:'1963– · Színész',                  img:'https://upload.wikimedia.org/wikipedia/commons/5/5e/Brad_Pitt_2019_by_Glenn_Francis.jpg' },
  { name:'Tom Hanks',            info:'1956– · Színész',                  img:'https://upload.wikimedia.org/wikipedia/commons/a/a9/Tom_Hanks_TIFF_2019.jpg' },
  { name:'Meryl Streep',         info:'1949– · Színésznő',                img:'https://upload.wikimedia.org/wikipedia/commons/2/26/Meryl_Streep_December_2018.jpg' },
  { name:'Johnny Depp',          info:'1963– · Színész',                  img:'https://upload.wikimedia.org/wikipedia/commons/2/27/Johnny_Depp_2020.jpg' },
  { name:'Scarlett Johansson',   info:'1984– · Színésznő',                img:'https://upload.wikimedia.org/wikipedia/commons/6/60/Scarlett_Johansson_2010.jpg' },
  { name:'Will Smith',           info:'1968– · Színész, rapper',          img:'https://upload.wikimedia.org/wikipedia/commons/3/3f/Will_Smith_2011.jpg' },
  { name:'Denzel Washington',    info:'1954– · Színész',                  img:'https://upload.wikimedia.org/wikipedia/commons/8/8e/Denzel_Washington_2012.jpg' },
  { name:'Morgan Freeman',       info:'1937– · Színész',                  img:'https://upload.wikimedia.org/wikipedia/commons/e/ee/Morgan_Freeman_2012.jpg' },
  { name:'Robert De Niro',       info:'1943– · Színész',                  img:'https://upload.wikimedia.org/wikipedia/commons/3/3c/Robert_De_Niro_-_Tribeca_Film_Festival_2011.jpg' },
  { name:'Al Pacino',            info:'1940– · Színész',                  img:'https://upload.wikimedia.org/wikipedia/commons/9/98/Al_Pacino.jpg' },
  { name:'Cate Blanchett',       info:'1969– · Színésznő',                img:'https://upload.wikimedia.org/wikipedia/commons/e/e1/Cate_Blanchett_Cannes_2018.jpg' },
  { name:'Natalie Portman',      info:'1981– · Színésznő',                img:'https://upload.wikimedia.org/wikipedia/commons/0/0d/Natalie_Portman_%28cropped%29.jpg' },
  { name:'Julia Roberts',        info:'1967– · Színésznő',                img:'https://upload.wikimedia.org/wikipedia/commons/5/51/Julia_Roberts_1995.jpg' },
  { name:'George Clooney',       info:'1961– · Színész',                  img:'https://upload.wikimedia.org/wikipedia/commons/8/8d/George_Clooney_2016.jpg' },
  { name:'Michael Jackson',      info:'1958–2009 · Énekes',               img:'https://upload.wikimedia.org/wikipedia/commons/3/31/Michael_Jackson_in_1988.jpg' },
  { name:'Madonna',              info:'1958– · Énekesnő',                 img:'https://upload.wikimedia.org/wikipedia/commons/a/a9/Madonna_in_NYC_-_1983_%28cropped%29.jpg' },
  { name:'Lady Gaga',            info:'1986– · Énekesnő',                 img:'https://upload.wikimedia.org/wikipedia/commons/1/11/Lady_Gaga_VMA_2013_%28cropped%29.jpg' },
  { name:'Beyoncé',              info:'1981– · Énekesnő',                 img:'https://upload.wikimedia.org/wikipedia/commons/1/17/Beyonc%C3%A9_at_The_Lion_King_European_Premiere_2019.png' },
  { name:'Taylor Swift',         info:'1989– · Énekesnő',                 img:'https://upload.wikimedia.org/wikipedia/commons/b/b5/191125_Taylor_Swift_at_the_2019_American_Music_Awards_%28cropped%29.png' },
  { name:'Eminem',               info:'1972– · Rapper',                   img:'https://upload.wikimedia.org/wikipedia/commons/9/9a/Eminem_gettyimages_crop.jpg' },
  { name:'Adele',                info:'1988– · Énekesnő',                 img:'https://upload.wikimedia.org/wikipedia/commons/6/6f/Adele_2016.jpg' },
  { name:'Rihanna',              info:'1988– · Énekesnő',                 img:'https://upload.wikimedia.org/wikipedia/commons/c/c3/Rihanna_BBMA_2011_%28cropped%29.jpg' },
  { name:'Justin Bieber',        info:'1994– · Énekes',                   img:'https://upload.wikimedia.org/wikipedia/commons/8/8e/Justin_Bieber_in_2015.jpg' },
  { name:'Kanye West',           info:'1977– · Rapper',                   img:'https://upload.wikimedia.org/wikipedia/commons/1/11/Kanye_West_at_the_2009_Tribeca_Film_Festival.jpg' },
  { name:'Drake',                info:'1986– · Rapper',                   img:'https://upload.wikimedia.org/wikipedia/commons/2/28/Drake_July_2016.jpg' },
  { name:'Ed Sheeran',           info:'1991– · Énekes',                   img:'https://upload.wikimedia.org/wikipedia/commons/b/b1/Ed_Sheeran_-_Multiply_Tour%2C_Hong_Kong_%28Kowloon%29.jpg' },
  { name:'Billie Eilish',        info:'2001– · Énekesnő',                 img:'https://upload.wikimedia.org/wikipedia/commons/b/ba/Billie_Eilish_%40_Osheaga_2019_-_Photo_by_Marika_Sherwood_%2848397800782%29_%28cropped%29.jpg' },
  { name:'Bruno Mars',           info:'1985– · Énekes',                   img:'https://upload.wikimedia.org/wikipedia/commons/2/27/Bruno_Mars_June_2013.jpg' },
  { name:'Ariana Grande',        info:'1993– · Énekesnő',                 img:'https://upload.wikimedia.org/wikipedia/commons/1/1d/Ariana_Grande_Grammys_Red_Carpet_2020.png' },
  { name:'The Weeknd',           info:'1990– · Énekes',                   img:'https://upload.wikimedia.org/wikipedia/commons/9/9a/The_Weeknd_in_2019.png' },
  { name:'Lionel Messi',         info:'1987– · Labdarúgó',                img:'https://upload.wikimedia.org/wikipedia/commons/b/b8/Messi_vs_Nigeria_2018.jpg' },
  { name:'Cristiano Ronaldo',    info:'1985– · Labdarúgó',                img:'https://upload.wikimedia.org/wikipedia/commons/8/8c/Cristiano_Ronaldo_2018.jpg' },
  { name:'LeBron James',         info:'1984– · Kosárlabdázó',             img:'https://upload.wikimedia.org/wikipedia/commons/c/cf/LeBron_James_crop.jpg' },
  { name:'Usain Bolt',           info:'1986– · Sprinter',                 img:'https://upload.wikimedia.org/wikipedia/commons/8/8e/Usain_Bolt_Olympics_cropped.jpg' },
  { name:'Roger Federer',        info:'1981– · Teniszező',                img:'https://upload.wikimedia.org/wikipedia/commons/4/40/Roger_Federer_-_2012_Wimbledon_%28cropped%29.jpg' },
  { name:'Serena Williams',      info:'1981– · Teniszező',                img:'https://upload.wikimedia.org/wikipedia/commons/3/36/Serena_Williams_at_the_2013_US_Open.jpg' },
  { name:'Tiger Woods',          info:'1975– · Golfozó',                  img:'https://upload.wikimedia.org/wikipedia/commons/2/2e/TigerWoods2018.jpg' },
  { name:'Kobe Bryant',          info:'1978–2020 · Kosárlabdázó',         img:'https://upload.wikimedia.org/wikipedia/commons/6/67/Kobe_Bryant_2014_%28cropped%29.jpg' },
  { name:'Pele',                 info:'1940–2022 · Labdarúgó',            img:'https://upload.wikimedia.org/wikipedia/commons/3/38/Pele_1970.jpg' },
  { name:'Mike Tyson',           info:'1966– · Bokszoló',                 img:'https://upload.wikimedia.org/wikipedia/commons/e/e1/Mike_Tyson_2019_by_Glenn_Francis.jpg' },
  { name:'Novak Djokovic',       info:'1987– · Teniszező',                img:'https://upload.wikimedia.org/wikipedia/commons/5/5f/Novak_Djokovic_2022.jpg' },
  { name:'Rafael Nadal',         info:'1986– · Teniszező',                img:'https://upload.wikimedia.org/wikipedia/commons/6/67/Rafael_Nadal_2020.jpg' },
  { name:'Zlatan Ibrahimovic',   info:'1981– · Labdarúgó',                img:'https://upload.wikimedia.org/wikipedia/commons/8/85/Zlatan_Ibrahimovic_2017.jpg' },
  { name:'Neymar',               info:'1992– · Labdarúgó',                img:'https://upload.wikimedia.org/wikipedia/commons/b/bc/Neymar_vs_Croatia_%28cropped%29.jpg' },
  { name:'Lewis Hamilton',       info:'1985– · F1-es versenyző',          img:'https://upload.wikimedia.org/wikipedia/commons/1/18/Lewis_Hamilton_2016_Malaysia_2.jpg' },
  { name:'Michael Schumacher',   info:'1969– · F1-es versenyző',          img:'https://upload.wikimedia.org/wikipedia/commons/9/97/Michael_Schumacher_2011.jpg' },
  { name:'Stephen Curry',        info:'1988– · Kosárlabdázó',             img:'https://upload.wikimedia.org/wikipedia/commons/3/35/Stephen_Curry_dribbling_2016_%28cropped%29.jpg' },
  { name:'Simone Biles',         info:'1997– · Tornász',                  img:'https://upload.wikimedia.org/wikipedia/commons/4/4a/Simone_Biles_at_the_2016_Summer_Olympics_%281%29.jpg' },
  { name:'Puskás Ferenc',        info:'1927–2006 · Labdarúgó',            img:'https://upload.wikimedia.org/wikipedia/commons/a/af/Ferenc_Puskas_1952.jpg' },
  { name:'Winston Churchill',    info:'1874–1965 · Politikus',            img:'https://upload.wikimedia.org/wikipedia/commons/b/bc/Sir_Winston_Churchill_-_19086236948.jpg' },
  { name:'Adolf Hitler',         info:'1889–1945 · Diktátor',             img:'https://upload.wikimedia.org/wikipedia/commons/a/a4/Adolf_Hitler_-_Berghof-1936_crop.jpg' },
  { name:'Joseph Stalin',        info:'1878–1953 · Politikus',            img:'https://upload.wikimedia.org/wikipedia/commons/6/6c/Stalin_1943.jpg' },
  { name:'Mao Zedong',           info:'1893–1976 · Politikus',            img:'https://upload.wikimedia.org/wikipedia/commons/3/32/Mao_Zedong_in_1959_%28cropped%29.jpg' },
  { name:'Che Guevara',          info:'1928–1967 · Forradalmár',          img:'https://upload.wikimedia.org/wikipedia/commons/5/58/CheHigh.jpg' },
  { name:'Nelson Mandela',       info:'1918–2013 · Politikus',            img:'https://upload.wikimedia.org/wikipedia/commons/0/02/Nelson_Mandela_1994.jpg' },
  { name:'Martin Luther King',   info:'1929–1968 · Polgárjogi aktivista', img:'https://upload.wikimedia.org/wikipedia/commons/0/05/Martin_Luther_King%2C_Jr..jpg' },
  { name:'Abraham Lincoln',      info:'1809–1865 · Politikus',            img:'https://upload.wikimedia.org/wikipedia/commons/a/ab/Abraham_Lincoln_O-77_matte_collodion_print.jpg' },
  { name:'John F. Kennedy',      info:'1917–1963 · Politikus',            img:'https://upload.wikimedia.org/wikipedia/commons/c/c3/John_F._Kennedy%2C_White_House_color_photo_portrait.jpg' },
  { name:'Vladimir Putin',       info:'1952– · Politikus',                img:'https://upload.wikimedia.org/wikipedia/commons/d/d7/Vladimir_Putin_%282020-02-20%29.jpg' },
  { name:'Donald Trump',         info:'1946– · Politikus',                img:'https://upload.wikimedia.org/wikipedia/commons/5/56/Donald_Trump_official_portrait.jpg' },
  { name:'Joe Biden',            info:'1942– · Politikus',                img:'https://upload.wikimedia.org/wikipedia/commons/6/68/Joe_Biden_presidential_portrait.jpg' },
  { name:'Angela Merkel',        info:'1954– · Politikus',                img:'https://upload.wikimedia.org/wikipedia/commons/b/bf/Angela_Merkel_2019_%28cropped%29.jpg' },
  { name:'Pope Francis',         info:'1936– · Pápa',                     img:'https://upload.wikimedia.org/wikipedia/commons/b/b2/Pope_Francis_Korea_Haemi_Castle_19.jpg' },
  { name:'Queen Elizabeth II',   info:'1926–2022 · Brit királynő',        img:'https://upload.wikimedia.org/wikipedia/commons/b/b6/Queen_Elizabeth_II_in_March_2015.jpg' },
  { name:'Dalai Láma',           info:'1935– · Vallási vezető',           img:'https://upload.wikimedia.org/wikipedia/commons/8/89/Official_portrait_of_the_Dalai_Lama.jpg' },
  { name:'Bill Gates',           info:'1955– · Vállalkozó',               img:'https://upload.wikimedia.org/wikipedia/commons/a/a8/Bill_Gates_2017_%28cropped%29.jpg' },
  { name:'Steve Jobs',           info:'1955–2011 · Vállalkozó',           img:'https://upload.wikimedia.org/wikipedia/commons/b/b9/Steve_Jobs_Headshot_2010-CROP_%28cropped_2%29.jpg' },
  { name:'Mark Zuckerberg',      info:'1984– · Vállalkozó',               img:'https://upload.wikimedia.org/wikipedia/commons/1/18/Mark_Zuckerberg_F8_2019_Keynote_%2832830578717%29_%28cropped%29.jpg' },
  { name:'Jeff Bezos',           info:'1964– · Vállalkozó',               img:'https://upload.wikimedia.org/wikipedia/commons/6/6f/Jeff_Bezos_2016.jpg' },
  { name:'Warren Buffett',       info:'1930– · Befektető',                img:'https://upload.wikimedia.org/wikipedia/commons/5/51/Warren_Buffett_KU_Visit.jpg' },
  { name:'Oprah Winfrey',        info:'1954– · Műsorvezető',              img:'https://upload.wikimedia.org/wikipedia/commons/b/bf/Oprah_in_2014.jpg' },
  { name:'Sigmund Freud',        info:'1856–1939 · Pszichológus',         img:'https://upload.wikimedia.org/wikipedia/commons/1/12/Sigmund_Freud_LIFE.jpg' },
  { name:'Karl Marx',            info:'1818–1883 · Filozófus',            img:'https://upload.wikimedia.org/wikipedia/commons/d/d4/Karl_Marx_001.jpg' },
  { name:'Friedrich Nietzsche',  info:'1844–1900 · Filozófus',            img:'https://upload.wikimedia.org/wikipedia/commons/1/1b/Nietzsche187a.jpg' },
  { name:'Plato',                info:'Kr.e. 428–348 · Filozófus',        img:'https://upload.wikimedia.org/wikipedia/commons/8/88/Plato_Silanion_Musei_Capitolini_MC1377.jpg' },
  { name:'Aristotle',            info:'Kr.e. 384–322 · Filozófus',        img:'https://upload.wikimedia.org/wikipedia/commons/a/ae/Aristotle_Altemps_Inv8575.jpg' },
  { name:'Socrates',             info:'Kr.e. 470–399 · Filozófus',        img:'https://upload.wikimedia.org/wikipedia/commons/b/bc/Socrate_du_Louvre.jpg' },
  { name:'Marie Curie',          info:'1867–1934 · Fizikus, kémikus',     img:'https://upload.wikimedia.org/wikipedia/commons/7/7e/Marie_Curie_c1920.jpg' },
  { name:'Louis Pasteur',        info:'1822–1895 · Mikrobiológus',        img:'https://upload.wikimedia.org/wikipedia/commons/e/ed/Louis_Pasteur%2C_foto_av_Nadar_Crisco_edit.jpg' },
  { name:'Galileo Galilei',      info:'1564–1642 · Csillagász',           img:'https://upload.wikimedia.org/wikipedia/commons/d/d4/Justus_Sustermans_-_Portrait_of_Galileo_Galilei%2C_1636.jpg' },
  { name:'Johannes Kepler',      info:'1571–1630 · Csillagász',           img:'https://upload.wikimedia.org/wikipedia/commons/d/d4/Johannes_Kepler_1610.jpg' },
  { name:'Alexander the Great',  info:'Kr.e. 356–323 · Hadvezér',        img:'https://upload.wikimedia.org/wikipedia/commons/4/40/AlexanderTheGreat_Bust.jpg' },
  { name:'Julius Caesar',        info:'Kr.e. 100–44 · Hadvezér',         img:'https://upload.wikimedia.org/wikipedia/commons/1/1b/CaesarTusculaniBust.jpg' },
  { name:'Cleopatra',            info:'Kr.e. 69–30 · Egyiptomi fáraó',   img:'https://upload.wikimedia.org/wikipedia/commons/3/3e/Cleopatra_VII_tetradrachm.jpg' },
  { name:'Genghis Khan',         info:'1162–1227 · Hadvezér',             img:'https://upload.wikimedia.org/wikipedia/commons/d/d6/Genghis_Khan.jpg' },
  { name:'Queen Victoria',       info:'1819–1901 · Brit királynő',        img:'https://upload.wikimedia.org/wikipedia/commons/e/e3/Queen_Victoria_by_Bassano.jpg' },
  { name:'William Shakespeare',  info:'1564–1616 · Drámaíró',             img:'https://upload.wikimedia.org/wikipedia/commons/a/a2/Shakespeare.jpg' },
  { name:'Charles Dickens',      info:'1812–1870 · Regényíró',            img:'https://upload.wikimedia.org/wikipedia/commons/a/a2/Charles_Dickens_-_Project_Gutenberg_eText_13103.jpg' },
  { name:'Ernest Hemingway',     info:'1899–1961 · Regényíró',            img:'https://upload.wikimedia.org/wikipedia/commons/2/28/ErnestHemingway.jpg' },
  { name:'Edgar Allan Poe',      info:'1809–1849 · Regényíró',            img:'https://upload.wikimedia.org/wikipedia/commons/d/d8/Edgar_Allan_Poe_2_-_edit1.jpg' },
  { name:'Mark Twain',           info:'1835–1910 · Regényíró',            img:'https://upload.wikimedia.org/wikipedia/commons/0/0c/Mark_Twain_by_AF_Bradley.jpg' },
  { name:'Oscar Wilde',          info:'1854–1900 · Drámaíró, regényíró',  img:'https://upload.wikimedia.org/wikipedia/commons/a/ab/Oscar_Wilde_portrait_by_Napoleon_Sarony.jpg' },
  { name:'Franz Kafka',          info:'1883–1924 · Regényíró',            img:'https://upload.wikimedia.org/wikipedia/commons/4/4c/Franz_Kafka%2C_1917.jpg' },
  { name:'J.R.R. Tolkien',       info:'1892–1973 · Regényíró',            img:'https://upload.wikimedia.org/wikipedia/commons/d/d4/J._R._R._Tolkien%2C_1940s.jpg' },
  { name:'Pablo Picasso',        info:'1881–1973 · Festő',                img:'https://upload.wikimedia.org/wikipedia/commons/b/b8/Portrait_de_Picasso%2C_1908.jpg' },
  { name:'Salvador Dalí',        info:'1904–1989 · Festő',                img:'https://upload.wikimedia.org/wikipedia/commons/2/21/Portrait_of_Salvador_Dal%C3%AD_%28cropped%29.jpg' },
  { name:'Michelangelo',         info:'1475–1564 · Szobrász, festő',      img:'https://upload.wikimedia.org/wikipedia/commons/5/5e/Miguel_%C3%81ngel%2C_por_Daniele_da_Volterra_%28detalle%29.jpg' },
  { name:'Rembrandt',            info:'1606–1669 · Festő',                img:'https://upload.wikimedia.org/wikipedia/commons/b/bd/Rembrandt_van_Rijn_-_Self-Portrait_-_Google_Art_Project.jpg' },
  { name:'Ludwig van Beethoven', info:'1770–1827 · Zeneszerző',           img:'https://upload.wikimedia.org/wikipedia/commons/6/6f/Beethoven.jpg' },
  { name:'Wolfgang A. Mozart',   info:'1756–1791 · Zeneszerző',           img:'https://upload.wikimedia.org/wikipedia/commons/4/47/Croce-Mozart-Detail.jpg' },
  { name:'Johann S. Bach',       info:'1685–1750 · Zeneszerző',           img:'https://upload.wikimedia.org/wikipedia/commons/6/6a/Johann_Sebastian_Bach.jpg' },
  { name:'Frédéric Chopin',      info:'1810–1849 · Zenszerző',            img:'https://upload.wikimedia.org/wikipedia/commons/e/e8/Frederic_Chopin_photo.jpeg' },
  { name:'Pyotr I. Tchaikovsky', info:'1840–1893 · Zenszerző',            img:'https://upload.wikimedia.org/wikipedia/commons/2/20/Tchaikovsky.jpg' },
  { name:'Stephen King',         info:'1947– · Regényíró',                img:'https://upload.wikimedia.org/wikipedia/commons/e/e3/Stephen_King%2C_Comicon.jpg' },
  { name:'J.K. Rowling',         info:'1965– · Regényíró',                img:'https://upload.wikimedia.org/wikipedia/commons/5/5b/J._K._Rowling_2010.jpg' },
  { name:'Agatha Christie',      info:'1890–1976 · Regényíró',            img:'https://upload.wikimedia.org/wikipedia/commons/c/cf/Agatha_Christie.png' },
  { name:'George Orwell',        info:'1903–1950 · Regényíró',            img:'https://upload.wikimedia.org/wikipedia/commons/7/7e/George_Orwell_press_photo.jpg' },
  { name:'Fyodor Dostoevsky',    info:'1821–1881 · Regényíró',            img:'https://upload.wikimedia.org/wikipedia/commons/3/3b/Dostoevsky.jpg' },
  { name:'Leo Tolstoy',          info:'1828–1910 · Regényíró',            img:'https://upload.wikimedia.org/wikipedia/commons/0/00/L.N.Tolstoy_Prokudin-Gorsky.jpg' },
  { name:'Victor Hugo',          info:'1802–1885 · Regényíró',            img:'https://upload.wikimedia.org/wikipedia/commons/8/8b/Victor_Hugo_by_Étienne_Carjat_1876_-_full.jpg' },
  { name:'Homer Simpson',        info:'Fikció · Animációs karakter',      img:'https://upload.wikimedia.org/wikipedia/en/0/02/Homer_Simpson_2006.png' },
  { name:'James Dean',           info:'1931–1955 · Színész',              img:'https://upload.wikimedia.org/wikipedia/commons/b/b3/James_Dean_in_Rebel_Without_a_Cause.jpg' },
  { name:'Marlon Brando',        info:'1924–2004 · Színész',              img:'https://upload.wikimedia.org/wikipedia/commons/9/9a/Marlon-Brando-1966.jpg' },
  { name:'Heath Ledger',         info:'1979–2008 · Színész',              img:'https://upload.wikimedia.org/wikipedia/commons/4/4e/Heathledger.jpg' },
  { name:'Robin Williams',       info:'1951–2014 · Színész',              img:'https://upload.wikimedia.org/wikipedia/commons/a/a7/Robin_Williams_Happy_Feet_premiere.jpg' },
  { name:'Jim Carrey',           info:'1962– · Színész',                  img:'https://upload.wikimedia.org/wikipedia/commons/6/6c/Jim_Carrey_2008_Cannes.jpg' },
  { name:'Arnold Schwarzenegger',info:'1947– · Színész, politikus',       img:'https://upload.wikimedia.org/wikipedia/commons/8/8e/Arnold_Schwarzenegger_2018.jpg' },
  { name:'Sylvester Stallone',   info:'1946– · Színész',                  img:'https://upload.wikimedia.org/wikipedia/commons/5/5c/Sylvester_Stallone_by_Gage_Skidmore_2_%28cropped%29.jpg' },
  { name:'Bruce Lee',            info:'1940–1973 · Harcos, színész',      img:'https://upload.wikimedia.org/wikipedia/commons/9/9a/Brucelee.jpg' },
  { name:'Jackie Chan',          info:'1954– · Színész, harcos',          img:'https://upload.wikimedia.org/wikipedia/commons/e/ec/Jackie_Chan_2011.jpg' },
  { name:'Keanu Reeves',         info:'1964– · Színész',                  img:'https://upload.wikimedia.org/wikipedia/commons/0/0d/Keanu_Reeves_2020.jpg' },
  { name:'Robert Downey Jr.',    info:'1965– · Színész',                  img:'https://upload.wikimedia.org/wikipedia/commons/9/94/Robert_Downey_Jr_2014_Comic_Con_%28cropped%29.jpg' },
  { name:'Dwayne Johnson',       info:'1972– · Színész, birkózó',         img:'https://upload.wikimedia.org/wikipedia/commons/1/1f/Dwayne_Johnson_2014_%28cropped%29.jpg' },
  { name:'Chris Evans',          info:'1981– · Színész',                  img:'https://upload.wikimedia.org/wikipedia/commons/3/3d/Chris_Evans_SDCC_2014.jpg' },
  { name:'Ryan Reynolds',        info:'1976– · Színész',                  img:'https://upload.wikimedia.org/wikipedia/commons/1/14/Ryan_Reynolds_2016.jpg' },
  { name:'Emma Watson',          info:'1990– · Színésznő',                img:'https://upload.wikimedia.org/wikipedia/commons/7/7f/Emma_Watson_2013.jpg' },
  { name:'Jennifer Lawrence',    info:'1990– · Színésznő',                img:'https://upload.wikimedia.org/wikipedia/commons/0/0e/Jennifer_Lawrence_at_the_83rd_Academy_Awards.jpg' },
  { name:'Charlize Theron',      info:'1975– · Színésznő',                img:'https://upload.wikimedia.org/wikipedia/commons/1/17/Charlize-theron-IMG_6081_%28cropped%29.jpg' },
  { name:'Halle Berry',          info:'1966– · Színésznő',                img:'https://upload.wikimedia.org/wikipedia/commons/8/8f/Halle_Berry_2010.jpg' },
  { name:'Jared Leto',           info:'1971– · Énekes, színész',          img:'https://upload.wikimedia.org/wikipedia/commons/4/40/Jared_Leto_2012.jpg' },
  { name:'Joaquin Phoenix',      info:'1974– · Színész',                  img:'https://upload.wikimedia.org/wikipedia/commons/e/e6/Joaquin_Phoenix_2018.jpg' },
  { name:'Cardi B',              info:'1992– · Rapper',                   img:'https://upload.wikimedia.org/wikipedia/commons/4/45/Cardi_B_2018.jpg' },
  { name:'Nicki Minaj',          info:'1982– · Rapper',                   img:'https://upload.wikimedia.org/wikipedia/commons/6/6b/Nicki_Minaj_at_Power_96.1_Jingle_Ball_2014_crop.jpg' },
  { name:'Post Malone',          info:'1995– · Rapper',                   img:'https://upload.wikimedia.org/wikipedia/commons/f/f0/Post_Malone_2019.jpg' },
  { name:'Snoop Dogg',           info:'1971– · Rapper',                   img:'https://upload.wikimedia.org/wikipedia/commons/e/e7/Snoop_Dogg_-_Presented_at_the_2019_Adult_Video_News_Awards.jpg' },
  { name:'Jay-Z',                info:'1969– · Rapper',                   img:'https://upload.wikimedia.org/wikipedia/commons/f/f6/Jay-Z_at_Cannes.jpg' },
  { name:'Kendrick Lamar',       info:'1987– · Rapper',                   img:'https://upload.wikimedia.org/wikipedia/commons/7/74/Kendrick_Lamar_-_2019_by_Glenn_Francis.jpg' },
  { name:'Shakira',              info:'1977– · Énekesnő',                 img:'https://upload.wikimedia.org/wikipedia/commons/4/40/Shakira_2022.jpg' },
  { name:'Jennifer Lopez',       info:'1969– · Énekesnő, színésznő',      img:'https://upload.wikimedia.org/wikipedia/commons/3/31/Jennifer_Lopez_2019_%28cropped%29.jpg' },
  { name:'Katy Perry',           info:'1984– · Énekesnő',                 img:'https://upload.wikimedia.org/wikipedia/commons/0/09/Katy_Perry_-_Prismatic_World_Tour_-_Rock_in_Rio_2015_%28cropped%29.jpg' },
  { name:'Dua Lipa',             info:'1995– · Énekesnő',                 img:'https://upload.wikimedia.org/wikipedia/commons/e/e4/Dua_Lipa_2021.jpg' },
  { name:'Harry Styles',         info:'1994– · Énekes',                   img:'https://upload.wikimedia.org/wikipedia/commons/b/b5/Harry_Styles_2020_%28cropped%29.jpg' },
  { name:'Shawn Mendes',         info:'1998– · Énekes',                   img:'https://upload.wikimedia.org/wikipedia/commons/e/eb/Shawn_Mendes_2018.jpg' },
  { name:'Sam Smith',            info:'1992– · Énekes',                   img:'https://upload.wikimedia.org/wikipedia/commons/3/35/Sam_Smith_2014_%28cropped%29.jpg' },
  { name:'Charlie Puth',         info:'1991– · Énekes',                   img:'https://upload.wikimedia.org/wikipedia/commons/d/de/Charlie_Puth_2018_%28cropped%29.jpg' },
  { name:'Elton John',           info:'1947– · Énekes, zenész',           img:'https://upload.wikimedia.org/wikipedia/commons/8/86/Elton_John_2010_%28cropped%29.jpg' },
  { name:'David Bowie',          info:'1947–2016 · Énekes',               img:'https://upload.wikimedia.org/wikipedia/commons/5/57/David-Bowie_earthlingera.jpg' },
  { name:'Prince',               info:'1958–2016 · Énekes',               img:'https://upload.wikimedia.org/wikipedia/commons/4/42/Prince_in_concert%2C_1985-cropped.jpg' },
  { name:'Jimi Hendrix',         info:'1942–1970 · Gitáros',              img:'https://upload.wikimedia.org/wikipedia/commons/7/7d/Jimi_Hendrix_1967_%28cropped%29.jpg' },
  { name:'Kurt Cobain',          info:'1967–1994 · Énekes',               img:'https://upload.wikimedia.org/wikipedia/commons/1/18/Kurt_Cobain_1991_cropped.jpg' },
  { name:'Jim Morrison',         info:'1943–1971 · Énekes',               img:'https://upload.wikimedia.org/wikipedia/commons/e/ed/Jim_Morrison_by_Paul_Ferrara.jpg' },
  { name:'Mick Jagger',          info:'1943– · Énekes',                   img:'https://upload.wikimedia.org/wikipedia/commons/4/49/Mick_Jagger_2016.jpg' },
  { name:'John Lennon',          info:'1940–1980 · Énekes',               img:'https://upload.wikimedia.org/wikipedia/commons/8/85/John_Lennon_1969_%28cropped%29.jpg' },
  { name:'Paul McCartney',       info:'1942– · Énekes',                   img:'https://upload.wikimedia.org/wikipedia/commons/1/11/Paul_McCartney_2008_Dallas.jpg' },
  { name:'Ringo Starr',          info:'1940– · Dobos',                    img:'https://upload.wikimedia.org/wikipedia/commons/5/5b/Ringo_Starr_2019.jpg' },
  { name:'George Harrison',      info:'1943–2001 · Gitáros',              img:'https://upload.wikimedia.org/wikipedia/commons/b/be/George_Harrison_1974.jpg' },
  { name:'Amy Winehouse',        info:'1983–2011 · Énekesnő',             img:'https://upload.wikimedia.org/wikipedia/commons/0/0b/Amy_Winehouse_f4962006.jpg' },
  { name:'Whitney Houston',      info:'1963–2012 · Énekesnő',             img:'https://upload.wikimedia.org/wikipedia/commons/3/36/Whitney_Houston_Welcome_Home_Heroes_1991.jpg' },
  { name:'Celine Dion',          info:'1968– · Énekesnő',                 img:'https://upload.wikimedia.org/wikipedia/commons/9/94/Celine_Dion_2012_%28cropped%29.jpg' },
  { name:'Mariah Carey',         info:'1969– · Énekesnő',                 img:'https://upload.wikimedia.org/wikipedia/commons/a/af/Mariah_Carey_2018_%28cropped%29.jpg' },
  { name:'Dolly Parton',         info:'1946– · Énekesnő',                 img:'https://upload.wikimedia.org/wikipedia/commons/e/e4/Dolly_Parton_2008.jpg' },
  { name:'Johnny Cash',          info:'1932–2003 · Énekes',               img:'https://upload.wikimedia.org/wikipedia/commons/b/b7/Johnny_Cash_-_1973.jpg' },
  { name:'Bruce Springsteen',    info:'1949– · Énekes',                   img:'https://upload.wikimedia.org/wikipedia/commons/2/26/Bruce_Springsteen_2012-2.jpg' },
  { name:'Bob Dylan',            info:'1941– · Énekes',                   img:'https://upload.wikimedia.org/wikipedia/commons/0/02/Bob_Dylan_-_Azkena_Rock_Festival_2010_%28front%29.jpg' },
  { name:'Neil Young',           info:'1945– · Énekes',                   img:'https://upload.wikimedia.org/wikipedia/commons/4/4d/Neil_Young_2008.jpg' },
  { name:'Eric Clapton',         info:'1945– · Gitáros',                  img:'https://upload.wikimedia.org/wikipedia/commons/8/87/Eric_Clapton_2009.jpg' },
  { name:'Ozzy Osbourne',        info:'1948– · Énekes',                   img:'https://upload.wikimedia.org/wikipedia/commons/1/10/Ozzy_Osbourne_2010.jpg' },
  { name:'Axl Rose',             info:'1962– · Énekes',                   img:'https://upload.wikimedia.org/wikipedia/commons/f/f7/Axl_Rose_2016.jpg' },
  { name:'Chester Bennington',   info:'1976–2017 · Énekes',               img:'https://upload.wikimedia.org/wikipedia/commons/1/18/Chester_Bennington_of_Linkin_Park.jpg' },
  { name:'Marilyn Manson',       info:'1969– · Énekes',                   img:'https://upload.wikimedia.org/wikipedia/commons/b/bf/Marilyn_Manson_2015.jpg' },
  { name:'Cristina Aguilera',    info:'1980– · Énekesnő',                 img:'https://upload.wikimedia.org/wikipedia/commons/f/f3/Christina_Aguilera_2012_%28cropped%29.jpg' },
  { name:'Pink',                 info:'1979– · Énekesnő',                 img:'https://upload.wikimedia.org/wikipedia/commons/d/d2/Pink_2012.jpg' },
  { name:'Miley Cyrus',          info:'1992– · Énekesnő',                 img:'https://upload.wikimedia.org/wikipedia/commons/0/0e/Miley_Cyrus_2019.jpg' },
  { name:'Selena Gomez',         info:'1992– · Énekesnő',                 img:'https://upload.wikimedia.org/wikipedia/commons/0/07/Selena_Gomez_2019.jpg' },
  { name:'Halsey',               info:'1994– · Énekesnő',                 img:'https://upload.wikimedia.org/wikipedia/commons/3/36/Halsey_at_Lollapalooza_2016_cropped.jpg' },
  { name:'Lewis Capaldi',        info:'1996– · Énekes',                   img:'https://upload.wikimedia.org/wikipedia/commons/a/a2/Lewis_Capaldi_2019.jpg' },
  { name:'Lorde',                info:'1996– · Énekesnő',                 img:'https://upload.wikimedia.org/wikipedia/commons/6/6e/Lorde_2017.jpg' },
  { name:'Olivia Rodrigo',       info:'2003– · Énekesnő',                 img:'https://upload.wikimedia.org/wikipedia/commons/8/8b/Olivia_Rodrigo_at_the_2021_Grammys_%28cropped%29.jpg' },
  { name:'SZA',                  info:'1989– · Énekesnő',                 img:'https://upload.wikimedia.org/wikipedia/commons/0/04/SZA_2017_by_Glenn_Francis.jpg' },
  { name:'Nicki Minaj',          info:'1982– · Rapper',                   img:'https://upload.wikimedia.org/wikipedia/commons/6/6b/Nicki_Minaj_at_Power_96.1_Jingle_Ball_2014_crop.jpg' },
  { name:'Zlatan Ibrahimovic',   info:'1981– · Labdarúgó',                img:'https://upload.wikimedia.org/wikipedia/commons/8/85/Zlatan_Ibrahimovic_2017.jpg' },
  { name:'Ronaldinho',           info:'1980– · Labdarúgó',                img:'https://upload.wikimedia.org/wikipedia/commons/6/63/Ronaldinho_2018.jpg' },
  { name:'Zinedine Zidane',      info:'1972– · Labdarúgó',                img:'https://upload.wikimedia.org/wikipedia/commons/f/f3/Zinedine_Zidane_2019.jpg' },
  { name:'David Beckham',        info:'1975– · Labdarúgó',                img:'https://upload.wikimedia.org/wikipedia/commons/9/98/David_Beckham_2014.jpg' },
  { name:'Wayne Rooney',         info:'1985– · Labdarúgó',                img:'https://upload.wikimedia.org/wikipedia/commons/2/22/Wayne_Rooney_2018.jpg' },
  { name:'Thierry Henry',        info:'1977– · Labdarúgó',                img:'https://upload.wikimedia.org/wikipedia/commons/d/de/Thierry_Henry_2019.jpg' },
  { name:'Kylian Mbappé',        info:'1998– · Labdarúgó',                img:'https://upload.wikimedia.org/wikipedia/commons/5/57/2019-07-17_SG_Dynamo_Dresden_vs._Paris_Saint-Germain_by_Sandro_Halank%E2%80%93278_%28crop%29.jpg' },
  { name:'Erling Haaland',       info:'2000– · Labdarúgó',                img:'https://upload.wikimedia.org/wikipedia/commons/4/43/Erling_Haaland_2022_%28cropped%29.jpg' },
  { name:'Phil Foden',           info:'2000– · Labdarúgó',                img:'https://upload.wikimedia.org/wikipedia/commons/5/5b/Phil_Foden_2020.jpg' },
  { name:'Vinícius Jr.',         info:'2000– · Labdarúgó',                img:'https://upload.wikimedia.org/wikipedia/commons/5/53/Vin%C3%ADcius_J%C3%BAnior_2022.jpg' },
  { name:'Maria Sharapova',      info:'1987– · Teniszező',                img:'https://upload.wikimedia.org/wikipedia/commons/b/b9/Maria_Sharapova_2014_US_Open.jpg' },
  { name:'Naomi Osaka',          info:'1997– · Teniszező',                img:'https://upload.wikimedia.org/wikipedia/commons/7/73/Naomi_Osaka_2019_US_Open.jpg' },
  { name:'Venus Williams',       info:'1980– · Teniszező',                img:'https://upload.wikimedia.org/wikipedia/commons/9/94/Venus_Williams_2013_US_Open.jpg' },
  { name:'Coco Gauff',           info:'2004– · Teniszező',                img:'https://upload.wikimedia.org/wikipedia/commons/9/91/Coco_Gauff_2021_Wimbledon_%28cropped%29.jpg' },
  { name:'Max Verstappen',       info:'1997– · F1-es versenyző',          img:'https://upload.wikimedia.org/wikipedia/commons/7/72/Max_Verstappen_2017_%28cropped%29.jpg' },
  { name:'Charles Leclerc',      info:'1997– · F1-es versenyző',          img:'https://upload.wikimedia.org/wikipedia/commons/b/b2/Charles_Leclerc_2019_%28cropped%29.jpg' },
  { name:'Valentino Rossi',      info:'1979– · Motoros versenyző',        img:'https://upload.wikimedia.org/wikipedia/commons/e/eb/Valentino_Rossi_2016_Assen.jpg' },
  { name:'Magnus Carlsen',       info:'1990– · Sakkozó',                  img:'https://upload.wikimedia.org/wikipedia/commons/b/b4/Magnus_Carlsen_in_2023.jpg' },
  { name:'Gary Kasparov',        info:'1963– · Sakkozó',                  img:'https://upload.wikimedia.org/wikipedia/commons/b/b6/Kasparov-27.jpg' },
  { name:'Conor McGregor',       info:'1988– · MMA-s harcos',             img:'https://upload.wikimedia.org/wikipedia/commons/6/64/Conor_McGregor_2019.jpg' },
  { name:'Ronda Rousey',         info:'1987– · MMA-s harcos',             img:'https://upload.wikimedia.org/wikipedia/commons/a/ab/Ronda_Rousey_2015_%28cropped%29.jpg' },
  { name:'Floyd Mayweather',     info:'1977– · Bokszoló',                 img:'https://upload.wikimedia.org/wikipedia/commons/e/ec/Floyd_Mayweather_Jr_2015.jpg' },
  { name:'Anthony Joshua',       info:'1989– · Bokszoló',                 img:'https://upload.wikimedia.org/wikipedia/commons/7/7e/Anthony_Joshua_2017_%28cropped%29.jpg' },
  { name:'Michael Phelps',       info:'1985– · Úszó',                     img:'https://upload.wikimedia.org/wikipedia/commons/8/83/Michael_Phelps_2012.jpg' },
  { name:'Katinka Hosszú',       info:'1989– · Úszó',                     img:'https://upload.wikimedia.org/wikipedia/commons/3/32/Katinka_Hosszu_2016.jpg' },
  { name:'Liu Xiang',            info:'1983– · Atléta',                   img:'https://upload.wikimedia.org/wikipedia/commons/8/84/Liu_Xiang_2007.jpg' },
  { name:'Nadia Comaneci',       info:'1961– · Tornász',                  img:'https://upload.wikimedia.org/wikipedia/commons/a/a4/Nadia_Comaneci_1976_Olympics.jpg' },
  { name:'Mark Spitz',           info:'1950– · Úszó',                     img:'https://upload.wikimedia.org/wikipedia/commons/9/97/Mark_Spitz_1972_Olympics.jpg' },
  { name:'Carl Lewis',           info:'1961– · Sprinter',                 img:'https://upload.wikimedia.org/wikipedia/commons/0/03/Carl_Lewis_1984_Olympics.jpg' },
  { name:'Jesse Owens',          info:'1913–1980 · Sprinter',             img:'https://upload.wikimedia.org/wikipedia/commons/b/b7/Jesse_Owens_1936.jpg' },
  { name:'Jack Nicholson',       info:'1937– · Színész',                  img:'https://upload.wikimedia.org/wikipedia/commons/d/d3/Jack_Nicholson_2002.jpg' },
  { name:'Clint Eastwood',       info:'1930– · Színész, rendező',         img:'https://upload.wikimedia.org/wikipedia/commons/e/ed/Clint_Eastwood_2010.jpg' },
  { name:'Harrison Ford',        info:'1942– · Színész',                  img:'https://upload.wikimedia.org/wikipedia/commons/e/e4/Harrison_Ford_2013.jpg' },
  { name:'Dustin Hoffman',       info:'1937– · Színész',                  img:'https://upload.wikimedia.org/wikipedia/commons/2/24/Dustin_Hoffman_2011.jpg' },
  { name:'Gene Hackman',         info:'1930– · Színész',                  img:'https://upload.wikimedia.org/wikipedia/commons/d/d5/Gene_Hackman_1971.jpg' },
  { name:'Sean Connery',         info:'1930–2020 · Színész',              img:'https://upload.wikimedia.org/wikipedia/commons/a/a4/Sean_Connery_1971.jpg' },
  { name:'Cary Grant',           info:'1904–1986 · Színész',              img:'https://upload.wikimedia.org/wikipedia/commons/3/30/CaryGrant1930s.jpg' },
  { name:'Humphrey Bogart',      info:'1899–1957 · Színész',              img:'https://upload.wikimedia.org/wikipedia/commons/a/ae/Humphrey_Bogart_1940.JPG' },
  { name:'Gregory Peck',         info:'1916–2003 · Színész',              img:'https://upload.wikimedia.org/wikipedia/commons/1/12/Gregory_Peck_in_1948.jpg' },
  { name:'Katharine Hepburn',    info:'1907–2003 · Színésznő',            img:'https://upload.wikimedia.org/wikipedia/commons/d/d1/Katharine_Hepburn_in_Adam%27s_Rib_trailer_%28cropped%29.JPG' },
  { name:'Grace Kelly',          info:'1929–1982 · Színésznő',            img:'https://upload.wikimedia.org/wikipedia/commons/b/b3/Grace_Kelly_1954.jpg' },
  { name:'Sophia Loren',         info:'1934– · Színésznő',                img:'https://upload.wikimedia.org/wikipedia/commons/c/cf/Sophia_Loren_-_1959.jpg' },
  { name:'Brigitte Bardot',      info:'1934– · Színésznő',                img:'https://upload.wikimedia.org/wikipedia/commons/e/e5/Brigitte_Bardot_1962.jpg' },
  { name:'Charlie Chaplin',      info:'1889–1977 · Színész, rendező',     img:'https://upload.wikimedia.org/wikipedia/commons/0/00/Charlie_Chaplin.jpg' },
  { name:'Buster Keaton',        info:'1895–1966 · Színész',              img:'https://upload.wikimedia.org/wikipedia/commons/b/b4/Buster_Keaton_in_The_General_cropped.jpg' },
  { name:'Alfred Hitchcock',     info:'1899–1980 · Filmrendező',          img:'https://upload.wikimedia.org/wikipedia/commons/a/a8/Alfred_Hitchcock_by_Jack_Mitchell.jpg' },
  { name:'Steven Spielberg',     info:'1946– · Filmrendező',              img:'https://upload.wikimedia.org/wikipedia/commons/8/8b/Steven_Spielberg_2016.jpg' },
  { name:'Stanley Kubrick',      info:'1928–1999 · Filmrendező',          img:'https://upload.wikimedia.org/wikipedia/commons/e/ef/Stanley_Kubrick_1949_%28cropped%29.jpg' },
  { name:'Martin Scorsese',      info:'1942– · Filmrendező',              img:'https://upload.wikimedia.org/wikipedia/commons/c/ce/Martin_Scorsese_2010.jpg' },
  { name:'Francis Ford Coppola', info:'1939– · Filmrendező',              img:'https://upload.wikimedia.org/wikipedia/commons/3/3e/Francis_Ford_Coppola_2011.jpg' },
  { name:'Christopher Nolan',    info:'1970– · Filmrendező',              img:'https://upload.wikimedia.org/wikipedia/commons/9/95/Christopher_Nolan_2018.png' },
  { name:'Tim Burton',           info:'1958– · Filmrendező',              img:'https://upload.wikimedia.org/wikipedia/commons/b/b9/Tim_Burton_2019_%28cropped%29.jpg' },
  { name:'Ridley Scott',         info:'1937– · Filmrendező',              img:'https://upload.wikimedia.org/wikipedia/commons/8/8b/Ridley_Scott_%282017%29.jpg' },
  { name:'Peter Jackson',        info:'1961– · Filmrendező',              img:'https://upload.wikimedia.org/wikipedia/commons/0/04/Peter_Jackson_2012.jpg' },
  { name:'James Cameron',        info:'1954– · Filmrendező',              img:'https://upload.wikimedia.org/wikipedia/commons/5/5d/James_Cameron_TIFF_2014.jpg' },
  { name:'Quentin Tarantino',    info:'1963– · Filmrendező',              img:'https://upload.wikimedia.org/wikipedia/commons/0/0b/Quentin_Tarantino_by_Gage_Skidmore.jpg' },
  { name:'David Fincher',        info:'1962– · Filmrendező',              img:'https://upload.wikimedia.org/wikipedia/commons/8/8c/David_Fincher_2010.jpg' },
  { name:'Wes Anderson',         info:'1969– · Filmrendező',              img:'https://upload.wikimedia.org/wikipedia/commons/8/83/Wes_Anderson_2014_%28cropped%29.jpg' },
  { name:'Rumi',                 info:'1207–1273 · Költő, misztikus',     img:'https://upload.wikimedia.org/wikipedia/commons/b/b7/Mevlana_Muzesi_Konya_2007.jpg' },
  { name:'Konfucius',            info:'Kr.e. 551–479 · Filozófus',        img:'https://upload.wikimedia.org/wikipedia/commons/4/4f/Confucius_Tang_Dynasty.jpg' },
  { name:'Buddha',               info:'Kr.e. 563–483 · Vallásalapító',    img:'https://upload.wikimedia.org/wikipedia/commons/f/f9/Dharmarajika_Stupa_Taxila.jpg' },
  { name:'Muhammad',             info:'570–632 · Próféta',                img:'https://upload.wikimedia.org/wikipedia/commons/a/ae/Calligraphic_representation_of_Muhammads_name.png' },
  { name:'Jézus Krisztus',       info:'Kr.e. 4 – Kr.u. 30 · Vallásos alak', img:'https://upload.wikimedia.org/wikipedia/commons/d/d6/Head_Christ_Colossal_statue_Baths_Caracalla_Pio-Clementino_Inv2223.jpg' },
  { name:'Marco Polo',           info:'1254–1324 · Felfedező',            img:'https://upload.wikimedia.org/wikipedia/commons/8/8b/MarcoPolo.jpg' },
  { name:'Christopher Columbus', info:'1451–1506 · Felfedező',            img:'https://upload.wikimedia.org/wikipedia/commons/5/5a/Christopher_Columbus.jpg' },
  { name:'Vasco da Gama',        info:'1460–1524 · Felfedező',            img:'https://upload.wikimedia.org/wikipedia/commons/6/6b/Vasco_da_Gama.jpg' },
  { name:'Ferdinand Magellan',   info:'1480–1521 · Felfedező',            img:'https://upload.wikimedia.org/wikipedia/commons/e/ea/Ferdinand_Magellan.jpg' },
  { name:'Neil Armstrong',       info:'1930–2012 · Asztronalta',          img:'https://upload.wikimedia.org/wikipedia/commons/0/0d/Neil_Armstrong_pose.jpg' },
  { name:'Yuri Gagarin',         info:'1934–1968 · Asztronaut',           img:'https://upload.wikimedia.org/wikipedia/commons/7/71/Yuri_Gagarin_%281961%29_-_Restoration.jpg' },
  { name:'Ada Lovelace',         info:'1815–1852 · Matematikus',          img:'https://upload.wikimedia.org/wikipedia/commons/a/a4/Ada_Lovelace_portrait.jpg' },
  { name:'Alan Turing',          info:'1912–1954 · Matematikus',          img:'https://upload.wikimedia.org/wikipedia/commons/a/a1/Alan_Turing_Aged_16.jpg' },
  { name:'Tim Berners-Lee',      info:'1955– · Informatikus',             img:'https://upload.wikimedia.org/wikipedia/commons/4/4e/Sir_Tim_Berners-Lee_%28cropped%29.jpg' },
  { name:'Linus Torvalds',       info:'1969– · Programozó',               img:'https://upload.wikimedia.org/wikipedia/commons/e/e8/Lc3_2018_%28263682303%29_%28cropped%29.jpeg' },
  { name:'Kip Thorne',           info:'1940– · Fizikus',                  img:'https://upload.wikimedia.org/wikipedia/commons/e/e4/Kip_Thorne_at_Caltech.jpg' },
  { name:'Richard Feynman',      info:'1918–1988 · Fizikus',              img:'https://upload.wikimedia.org/wikipedia/commons/1/1a/RichardFeynman-PaineMansionWoods1984_copyrighted.jpg' },
  { name:'Carl Sagan',           info:'1934–1996 · Csillagász',           img:'https://upload.wikimedia.org/wikipedia/commons/b/be/Carl_Sagan_Planetary_Society.JPG' },
  { name:'Neil deGrasse Tyson',  info:'1958– · Asztrofizikus',            img:'https://upload.wikimedia.org/wikipedia/commons/8/82/Neil_deGrasse_Tyson_2.jpg' },
  { name:'Jane Goodall',         info:'1934– · Etológus',                 img:'https://upload.wikimedia.org/wikipedia/commons/f/f3/Jane_Goodall_2015.jpg' },
  { name:'David Attenborough',   info:'1926– · Természettudós',           img:'https://upload.wikimedia.org/wikipedia/commons/6/69/David_Attenborough_2011.jpg' },
  { name:'Elon Musk',            info:'1971– · Vállalkozó',               img:'https://upload.wikimedia.org/wikipedia/commons/3/34/Elon_Musk_Royal_Society_%28crop2%29.jpg' },
  { name:'Satya Nadella',        info:'1967– · Vállalkozó',               img:'https://upload.wikimedia.org/wikipedia/commons/7/78/Satya_nadella_cropped.jpg' },
  { name:'Sundar Pichai',        info:'1972– · Vállalkozó',               img:'https://upload.wikimedia.org/wikipedia/commons/b/b6/Sundar_Pichai_2015.jpg' },
  { name:'Jack Ma',              info:'1964– · Vállalkozó',               img:'https://upload.wikimedia.org/wikipedia/commons/7/7a/Jack_Ma_WEF_Davos_2014.jpg' },
  { name:'Larry Page',           info:'1973– · Vállalkozó',               img:'https://upload.wikimedia.org/wikipedia/commons/e/ee/Larry_Page_in_the_European_Parliament%2C_17.06.2009_%28cropped%29.jpg' },
  { name:'Sergey Brin',          info:'1973– · Vállalkozó',               img:'https://upload.wikimedia.org/wikipedia/commons/2/2a/Sergey_Brin_at_the_2014_New_York_Toy_Fair_%28cropped%29.jpg' },
  { name:'Jensen Huang',         info:'1963– · Vállalkozó',               img:'https://upload.wikimedia.org/wikipedia/commons/7/70/Jensen_Huang_2019.jpg' },
];
// Shuffle once per page load
(()=>{ for(let i=KIVAGYOK_CELEBS.length-1;i>0;i--){ const j=Math.floor(Math.random()*(i+1)); [KIVAGYOK_CELEBS[i],KIVAGYOK_CELEBS[j]]=[KIVAGYOK_CELEBS[j],KIVAGYOK_CELEBS[i]]; } })();"""

start = content.index('const KIVAGYOK_CELEBS = [')
end = content.index('];', start) + 2
old_block = content[start:end]
content = content.replace(old_block, NEW_CELEBS, 1)

assert 'Verzió 5.75' in content
content = content.replace('Verzió 5.75', 'Verzió 5.76', 1)

with open('index.html', 'w', encoding='utf-8') as f:
    f.write(content)

print(f'OK — KIVAGYOK_CELEBS updated, v5.76')
